"""Where explore search's ranking parameters come from.

Every tunable in this feature is generated data, not a typed-in number.
There is exactly one exception, a published result rather than a property
of this corpus, in `document_authority` with its citation: PageRank's
damping 0.85 (Brin & Page, 1998). Reciprocal rank fusion's K used to be a
second (Cormack, Clarke & Büttcher's 60); it is now measured too (rrf_k).

Three sources, in order:

1. **The database.** The explore pipeline recalibrates against the corpus
   it just ingested and stores the result (`calibrate_and_store`). After
   the first nightly run, every value in use was derived from production
   data. This is the normal case.
2. **The bundled JSON** (`app/data/explore_ranking.json`), generated by
   `scripts/calibrate_explore_ranking.py`. It covers the window between a
   fresh deploy and that first pipeline run — the same role the bundled
   `district_pvi.json` plays before its first ingest.
3. **Nothing.** If both are missing the loaders raise, rather than ranking
   with invented numbers. A ranking that silently falls back to made-up
   weights is worse than one that refuses to start.

The derivations themselves live in `calibrate_ranking.py`, whose module
docstring explains what each value is measured from. This module is only
the plumbing.
"""

from __future__ import annotations

import json
import logging
import pathlib
import threading

from app.shared_state import PolledRow, decode_json_dict

logger = logging.getLogger(__name__)

_BUNDLED = pathlib.Path(__file__).resolve().parent.parent / "data" / "explore_ranking.json"

_CACHE_NAMESPACE = "explore"
_CACHE_KEY = "ranking_calibration"

# The keys every consumer needs present for a calibration to be usable.
_REQUIRED_KEYS = frozenset({
    "field_weights", "prior_weights", "candidate_pool", "retriever_resolution_ranks",
    "source_diversity_cap", "fingerprint", "text_shape",
})

# How often a process checks whether the stored calibration was replaced.
# The explore pipeline recalibrates in the pipeline process, and its
# reset_cache() reaches only that process; Explore search runs in the API
# processes (settings.PROCESS_ROLE), which notice the new row's timestamp
# (shared_state.PolledRow).
_CHECK_STORED_EVERY_SECONDS = 30

_lock = threading.Lock()
_bundled: dict | None = None


class RankingCalibrationMissing(RuntimeError):
    """Neither the database nor the bundled file has a calibration."""


def _stored(db=None):
    """The stored calibration row: (written at, value), None, or UNREADABLE
    (shared_state.read_row — read whatever its age: a calibration stands
    until the explore pipeline replaces it)."""
    from app.shared_state import read_row

    return read_row(_CACHE_NAMESPACE, _CACHE_KEY, db)


# Read through _stored at call time, so a test can stand in for the row.
_calibration = PolledRow(
    _CACHE_NAMESPACE, _CACHE_KEY, every_s=_CHECK_STORED_EVERY_SECONDS,
    decode=decode_json_dict, reader=lambda db: _stored(db),
)


def _load_bundled() -> dict | None:
    try:
        return json.loads(_BUNDLED.read_text())
    except (OSError, ValueError):
        return None


def ranking(*, force_reload: bool = False) -> dict:
    """The calibration in force, database first, bundled file second."""
    global _bundled

    # A complete override stands alone — that is what lets the very first
    # calibration run on a corpus that has never been calibrated, with
    # nothing yet in the database or the bundled file to fall back to.
    if _override is not None and set(_override) >= _REQUIRED_KEYS:
        return _override

    stored = _calibration.get(force=force_reload)
    if stored is not None:
        return _with_override(stored)
    # No stored calibration (or none readable yet): the bundled one, read
    # once per process — it changes only with a deploy.
    with _lock:
        bundled = _bundled
    if bundled is None or force_reload:
        bundled = _load_bundled()
        with _lock:
            _bundled = bundled
    if not bundled:
        raise RankingCalibrationMissing(
            "No explore ranking calibration available. Run "
            "backend/scripts/calibrate_explore_ranking.py --write, or run "
            "the explore pipeline, which calibrates as its last step."
        )
    return _with_override(bundled)


def _with_override(calibration: dict) -> dict:
    # Merged on every return, not only a cache miss. Overriding one key
    # against a warm cache used to be silently ignored, which would have
    # made a weight sweep compare a trial value against itself and report
    # the starting point as the fitted answer.
    return {**calibration, **_override} if _override else calibration


_override: dict | None = None


def override(values: dict):
    """Temporarily force calibration values.

    Used only while *deriving* them: fitting BM25F field weights means
    running retrieval under a trial set, and measuring a prior's coverage
    means running retrieval with the priors off. Both need to change what
    the ranker reads without persisting anything.
    """
    from contextlib import contextmanager

    @contextmanager
    def _ctx():
        global _override
        previous = _override
        _override = {**(previous or {}), **values}
        try:
            yield
        finally:
            _override = previous

    return _ctx()


def reset_cache() -> None:
    """Drop the in-process cache (used after a pipeline recalibration)."""
    global _bundled
    _calibration.reset()
    with _lock:
        _bundled = None


# ── typed accessors ──────────────────────────────────────────────

def field_weights() -> dict[str, float]:
    """BM25F field weights (Robertson & Zaragoza 2009 §3.2), fitted by
    coordinate ascent on known-item retrieval MRR over the live corpus."""
    return ranking()["field_weights"]


def fusion_weights() -> dict[str, float]:
    """Weight per ranker in the RRF sum.

    Both retrieval channels carry the published unweighted value; the two
    priors are derived from the retrievers' measured resolution limit and
    each prior's measured coverage of the corpus.
    """
    from app.config_definitions import EXPLORE_RETRIEVAL_WEIGHT

    priors = ranking()["prior_weights"]
    return {
        "semantic": EXPLORE_RETRIEVAL_WEIGHT,
        "keyword": EXPLORE_RETRIEVAL_WEIGHT,
        "freshness": priors["freshness"],
        "authority": priors["authority"],
    }


def rrf_k(delta: float | None = None) -> float:
    """Reciprocal rank fusion's K: the retrievers' resolution δ (the median
    rank disagreement between the two channels on documents both return,
    calibrate_ranking.derive_retriever_resolution), at least 1.

    K sets how slowly a channel's contribution falls off with rank. Ranks
    closer than δ are below what the retrievers can tell apart, and ranks
    many δ down are noise, so K is put on that scale: a channel's first hit
    counts about twice its hit δ ranks lower. With the published K = 60 a
    document two channels both placed around 30th outscored one channel's
    first hit, and the known-item harness showed it (2026-10-08, 9,458
    documents, δ = 10, 1,516 probes over two samples): fusion found the
    target first 36-40% of the time against the keyword channel's 66-68%, and
    missed 17% of targets against the keyword channel's 4-5%. K = δ lifted fusion
    and hybrid on every query style (see the PR that made this change, and
    scripts/evaluate_explore_search.py). Smaller K scored higher still on
    known-item probes, which reward trusting a lone top hit; K is the
    measured δ, not the harness's best value.
    """
    if delta is None:
        delta = float(ranking()["retriever_resolution_ranks"])
    return max(1.0, float(delta))


def candidate_pool() -> tuple[int, int]:
    """(default, max) candidates per channel, from measured filter survival."""
    pool = ranking()["candidate_pool"]
    return int(pool["default"]), int(pool["max"])


def source_diversity_cap() -> int:
    """Documents per member/agency before the rest are demoted, from the
    corpus's own median documents-per-source."""
    return int(ranking()["source_diversity_cap"])


def fingerprint_shape() -> tuple[int, int]:
    """(prefix chars, minimum chars) for near-duplicate detection, read off
    the corpus's prefix-collision curve."""
    fp = ranking()["fingerprint"]
    return int(fp["prefix_chars"]), int(fp["min_chars"])


def text_shape() -> tuple[int, int]:
    """(snippet tokens, minimum term length) — the corpus's median sentence
    length, and the shortest term length that is not near-universal."""
    shape = ranking()["text_shape"]
    return int(shape["snippet_tokens"]), int(shape["min_term_length"])


def calibrate_and_store(db) -> dict | None:
    """Recalibrate against the current corpus and persist the result.

    Called at the end of the explore ingest pipeline, so the parameters
    always describe the corpus actually being searched. Returns the stored
    calibration, or None if it could not be computed — in which case the
    previous one stays in force, which is the right failure mode: a stale
    calibration ranks worse than a fresh one, and far better than none.
    """
    from app.pipeline.calibrate_ranking import compute_calibration
    from app.pipeline.vector_store import index_is_whole, is_busy_error

    try:
        whole = index_is_whole()
    except Exception as error:
        if is_busy_error(error):
            logger.warning("Explore vector index busy — keeping the previous ranking calibration")
        else:
            logger.exception("Explore vector index unreadable — keeping the previous ranking calibration")
        return None
    if not whole:
        # The semantic channel answers nothing while its index isn't a
        # complete build: measured against it, the priors come out as if the
        # channels agreed perfectly (freshness and authority 0).
        logger.warning("Explore vector index not ready — keeping the previous ranking calibration")
        return None
    try:
        payload = compute_calibration(db)
    except Exception:
        logger.exception("Explore ranking calibration failed — keeping the previous one")
        return None

    if not payload:
        return None

    from app.pipeline.cache import api_cache_set

    api_cache_set(db, _CACHE_NAMESPACE, _CACHE_KEY, json.dumps(payload))
    db.commit()
    reset_cache()
    logger.info(
        "Recalibrated explore ranking: field=%s priors=%s pool=%s cap=%s",
        payload.get("field_weights"), payload.get("prior_weights"),
        payload.get("candidate_pool"), payload.get("source_diversity_cap"),
    )
    return payload
