"""Where explore search's ranking parameters come from.

Every tunable in this feature is generated data, not a typed-in number.
There are exactly two exceptions, both published results rather than
properties of this corpus, and both live in `config_definitions` with
their citations: reciprocal rank fusion's K = 60 (Cormack, Clarke &
Büttcher, SIGIR 2009) and PageRank's damping 0.85 (Brin & Page, 1998).

Three sources, in order:

1. **The database.** The explore pipeline recalibrates against the corpus
   it just ingested and stores the result (`calibrate_and_store`). After
   the first nightly run, every value in use was derived from production
   data. This is the normal case.
2. **The bundled JSON** (`app/data/explore_ranking.json`), generated by
   `scripts/calibrate_explore_ranking.py`. It covers the window between a
   fresh deploy and that first pipeline run — the same role the bundled
   `district_pvi.json` plays before its first ingest.
3. **Nothing.** If both are missing the loaders raise, rather than ranking
   with invented numbers. A ranking that silently falls back to made-up
   weights is worse than one that refuses to start.

The derivations themselves live in `calibrate_ranking.py`, whose module
docstring explains what each value is measured from. This module is only
the plumbing.
"""

from __future__ import annotations

import json
import logging
import pathlib
import threading
import time

logger = logging.getLogger(__name__)

_BUNDLED = pathlib.Path(__file__).resolve().parent.parent / "data" / "explore_ranking.json"

_CACHE_NAMESPACE = "explore"
_CACHE_KEY = "ranking_calibration"

# How long a loaded calibration is reused before the database is consulted
# again. Not a tuning value: the calibration changes at most once per
# nightly pipeline run, and this only bounds how long a running process
# keeps serving the previous one.
_RELOAD_AFTER_SECONDS = 3600

# The keys every consumer needs present for a calibration to be usable.
_REQUIRED_KEYS = frozenset({
    "field_weights", "prior_weights", "candidate_pool",
    "source_diversity_cap", "fingerprint", "text_shape",
})

_lock = threading.Lock()
_cached: dict | None = None
_cached_at: float = 0.0


class RankingCalibrationMissing(RuntimeError):
    """Neither the database nor the bundled file has a calibration."""


def _load_from_db() -> dict | None:
    try:
        from app.database import SessionLocal
        from app.pipeline.cache import api_cache_get

        db = SessionLocal()
        try:
            raw = api_cache_get(db, _CACHE_NAMESPACE, _CACHE_KEY)
        finally:
            db.close()
        if isinstance(raw, dict):
            return raw
        if isinstance(raw, str):
            return json.loads(raw)
    except Exception:
        logger.debug("No stored ranking calibration; using the bundled one",
                     exc_info=True)
    return None


def _load_bundled() -> dict | None:
    try:
        return json.loads(_BUNDLED.read_text())
    except (OSError, ValueError):
        return None


def ranking(*, force_reload: bool = False) -> dict:
    """The calibration in force, database first, bundled file second."""
    global _cached, _cached_at

    # A complete override stands alone — that is what lets the very first
    # calibration run on a corpus that has never been calibrated, with
    # nothing yet in the database or the bundled file to fall back to.
    if _override is not None and set(_override) >= _REQUIRED_KEYS:
        return _override

    with _lock:
        fresh = _cached is not None and (time.monotonic() - _cached_at) < _RELOAD_AFTER_SECONDS
        if fresh and not force_reload:
            # Merge here too, not only on a cache miss. Overriding one key
            # against a warm cache used to be silently ignored, which would
            # have made a weight sweep compare a trial value against itself
            # and report the starting point as the fitted answer.
            return {**_cached, **_override} if _override else _cached

        loaded = _load_from_db() or _load_bundled()
        if not loaded:
            raise RankingCalibrationMissing(
                "No explore ranking calibration available. Run "
                "backend/scripts/calibrate_explore_ranking.py --write, or run "
                "the explore pipeline, which calibrates as its last step."
            )
        _cached, _cached_at = loaded, time.monotonic()
        return {**_cached, **_override} if _override else _cached


_override: dict | None = None


def override(values: dict):
    """Temporarily force calibration values.

    Used only while *deriving* them: fitting BM25F field weights means
    running retrieval under a trial set, and measuring a prior's coverage
    means running retrieval with the priors off. Both need to change what
    the ranker reads without persisting anything.
    """
    from contextlib import contextmanager

    @contextmanager
    def _ctx():
        global _override
        previous = _override
        _override = {**(previous or {}), **values}
        try:
            yield
        finally:
            _override = previous

    return _ctx()


def reset_cache() -> None:
    """Drop the in-process cache (used after a pipeline recalibration)."""
    global _cached, _cached_at
    with _lock:
        _cached, _cached_at = None, 0.0


# ── typed accessors ──────────────────────────────────────────────

def field_weights() -> dict[str, float]:
    """BM25F field weights (Robertson & Zaragoza 2009 §3.2), fitted by
    coordinate ascent on known-item retrieval MRR over the live corpus."""
    return ranking()["field_weights"]


def fusion_weights() -> dict[str, float]:
    """Weight per ranker in the RRF sum.

    Both retrieval channels carry the published unweighted value; the two
    priors are derived from the retrievers' measured resolution limit and
    each prior's measured coverage of the corpus.
    """
    from app.config_definitions import EXPLORE_RETRIEVAL_WEIGHT

    priors = ranking()["prior_weights"]
    return {
        "semantic": EXPLORE_RETRIEVAL_WEIGHT,
        "keyword": EXPLORE_RETRIEVAL_WEIGHT,
        "freshness": priors["freshness"],
        "authority": priors["authority"],
    }


def candidate_pool() -> tuple[int, int]:
    """(default, max) candidates per channel, from measured filter survival."""
    pool = ranking()["candidate_pool"]
    return int(pool["default"]), int(pool["max"])


def source_diversity_cap() -> int:
    """Documents per member/agency before the rest are demoted, from the
    corpus's own median documents-per-source."""
    return int(ranking()["source_diversity_cap"])


def fingerprint_shape() -> tuple[int, int]:
    """(prefix chars, minimum chars) for near-duplicate detection, read off
    the corpus's prefix-collision curve."""
    fp = ranking()["fingerprint"]
    return int(fp["prefix_chars"]), int(fp["min_chars"])


def text_shape() -> tuple[int, int]:
    """(snippet tokens, minimum term length) — the corpus's median sentence
    length, and the shortest term length that is not near-universal."""
    shape = ranking()["text_shape"]
    return int(shape["snippet_tokens"]), int(shape["min_term_length"])


def calibrate_and_store(db) -> dict | None:
    """Recalibrate against the current corpus and persist the result.

    Called at the end of the explore ingest pipeline, so the parameters
    always describe the corpus actually being searched. Returns the stored
    calibration, or None if it could not be computed — in which case the
    previous one stays in force, which is the right failure mode: a stale
    calibration ranks worse than a fresh one, and far better than none.
    """
    from app.pipeline.calibrate_ranking import compute_calibration

    try:
        payload = compute_calibration(db)
    except Exception:
        logger.exception("Explore ranking calibration failed — keeping the previous one")
        return None

    if not payload:
        return None

    from app.pipeline.cache import api_cache_set

    api_cache_set(db, _CACHE_NAMESPACE, _CACHE_KEY, json.dumps(payload))
    db.commit()
    reset_cache()
    logger.info(
        "Recalibrated explore ranking: field=%s priors=%s pool=%s cap=%s",
        payload.get("field_weights"), payload.get("prior_weights"),
        payload.get("candidate_pool"), payload.get("source_diversity_cap"),
    )
    return payload
