import type { CSSProperties } from "react";
import localFont from "next/font/local";

/* The site's three typefaces, committed to the repo rather than fetched
   from Google Fonts while `next build` runs.

   next/font/google downloads fonts at build time, and about one build in
   five failed there: Google intermittently answers with a
   `fonts.gstatic.com/l/font?kit=…` URL that Turbopack's loader rejects
   ("queries have exactly one entry"). The files in ./fonts are the ones
   that loader downloaded — byte-for-byte, fetched with its User-Agent by
   backend/scripts/fetch_site_fonts.py, which also records Google's
   unicode-range for each file in ./fonts/manifest.json (fonts.test.ts
   holds this file to it). Rerun that script to update a face.

   Google splits each family into one file per script behind a
   unicode-range, so a page downloads only the scripts its text uses. That
   is kept: next/font/local applies one unicode-range per call, so each
   subset is its own call, and the CSS variable is assembled below with
   every subset face ahead of the fallback. Anywhere earlier, the fallback
   (a local() face with no unicode-range) would take every character the
   latin face lacks. Only the latin subsets are preloaded, as with
   next/font/google's `subsets: ["latin"]`.

   Under Turbopack the emitted font-family is the const's name
   (`archivoLatin`), so renaming a const renames the family; nothing
   outside this file names one. Options must be literals — next/font reads
   them at compile time — hence the repeated ranges. */

// Display and prose. 400 for body, 600 for headings, 800 for the blunt
// statement type the masthead is built on — a grotesque at heavy weight
// reads broadsheet and poster, where a bookish serif reads endowment.
// One variable file per subset, declared at the three weights Google's
// CSS declares it at, so any other weight resolves the way it did before.
//
// No generated fallback: next/font/local would measure this file at its
// default instance, which is wght 600, and size the Arial fallback for
// SemiBold — about 4% too wide for 400-weight prose, which then reflows
// when Archivo arrives. fonts/fallback.css (generated by the fetch script,
// measured at 400) supplies it instead.
const archivoLatin = localFont({
  src: [
    { path: "./fonts/archivo-latin.woff2", weight: "400" },
    { path: "./fonts/archivo-latin.woff2", weight: "600" },
    { path: "./fonts/archivo-latin.woff2", weight: "800" },
  ],
  adjustFontFallback: false,
  declarations: [
    {
      prop: "unicode-range",
      value:
        "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    },
  ],
});

const archivoLatinExt = localFont({
  src: [
    { path: "./fonts/archivo-latin-ext.woff2", weight: "400" },
    { path: "./fonts/archivo-latin-ext.woff2", weight: "600" },
    { path: "./fonts/archivo-latin-ext.woff2", weight: "800" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    {
      prop: "unicode-range",
      value:
        "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF",
    },
  ],
});

const archivoVietnamese = localFont({
  src: [
    { path: "./fonts/archivo-vietnamese.woff2", weight: "400" },
    { path: "./fonts/archivo-vietnamese.woff2", weight: "600" },
    { path: "./fonts/archivo-vietnamese.woff2", weight: "800" },
  ],
  preload: false,
  adjustFontFallback: false,
  declarations: [
    {
      prop: "unicode-range",
      value:
        "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+0300-0301, U+0303-0304, U+0308-0309, U+0323, U+0329, U+1EA0-1EF9, U+20AB",
    },
  ],
});

const pressStartLatin = localFont({
  src: "./fonts/press-start-2p-latin.woff2",
  weight: "400",
  declarations: [
    {
      prop: "unicode-range",
      value:
        "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    },
  ],
});

const pressStartLatinExt = localFont({
  src: "./fonts/press-start-2p-latin-ext.woff2",
  weight: "400",
  preload: false,
  adjustFontFallback: false,
  declarations: [
    {
      prop: "unicode-range",
      value:
        "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF",
    },
  ],
});

const pressStartCyrillic = localFont({
  src: "./fonts/press-start-2p-cyrillic.woff2",
  weight: "400",
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: "unicode-range", value: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116" },
  ],
});

const pressStartCyrillicExt = localFont({
  src: "./fonts/press-start-2p-cyrillic-ext.woff2",
  weight: "400",
  preload: false,
  adjustFontFallback: false,
  declarations: [
    {
      prop: "unicode-range",
      value: "U+0460-052F, U+1C80-1C8A, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
    },
  ],
});

const pressStartGreek = localFont({
  src: "./fonts/press-start-2p-greek.woff2",
  weight: "400",
  preload: false,
  adjustFontFallback: false,
  declarations: [
    {
      prop: "unicode-range",
      value: "U+0370-0377, U+037A-037F, U+0384-038A, U+038C, U+038E-03A1, U+03A3-03FF",
    },
  ],
});

// Share Tech Mono has only a latin subset on Google Fonts, so it is a
// single call and keeps next/font's own CSS variable.
export const shareTech = localFont({
  src: "./fonts/share-tech-mono-latin.woff2",
  weight: "400",
  variable: "--font-share-tech",
  declarations: [
    {
      prop: "unicode-range",
      value:
        "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
    },
  ],
});

type LoadedFont = { style: { fontFamily: string } };

/** Splits a next/font `fontFamily` value ("'a', 'a Fallback'") into its
 *  names. Family names never contain a comma. */
function families(font: LoadedFont): string[] {
  return font.style.fontFamily.split(",").map((name) => name.trim());
}

/** One family stack for a typeface split across subset calls: every
 *  subset's face, then their fallbacks, then any fallback named here. */
export function familyStack(faces: LoadedFont[], ...fallbacks: string[]): string {
  const names = faces.map(families);
  return [
    ...names.map(([face]) => face),
    ...names.flatMap(([, ...rest]) => rest),
    ...fallbacks,
  ].join(", ");
}

/** The family fonts/fallback.css declares. */
export const ARCHIVO_FALLBACK = "Archivo Fallback";

/** The two split typefaces' CSS variables, set on <body> where next/font
 *  would put a `variable` class (lib/shareImage.ts reads them there). */
export const fontVariables = {
  "--font-archivo": familyStack(
    [archivoLatin, archivoLatinExt, archivoVietnamese],
    `'${ARCHIVO_FALLBACK}'`
  ),
  "--font-press-start": familyStack([
    pressStartLatin,
    pressStartLatinExt,
    pressStartCyrillic,
    pressStartCyrillicExt,
    pressStartGreek,
  ]),
} as CSSProperties;
