"""
Bill analyzer — hybrid classification using embeddings + LLM.

Policy area classification (HEALTHCARE, DEFENSE, etc.) uses cosine similarity
between the bill text and pre-computed policy area embeddings. This is fast,
deterministic, and doesn't require an LLM call.

Stance, impact, and description require reasoning and are generated by the LLM.
Bills that are clearly procedural (nominations, cloture) are classified without
LLM entirely using keyword detection.

This reduces LLM calls by ~30-40% compared to the prior approach of sending
every bill through the LLM individually.
"""

import logging
from typing import Any

import numpy as np

from app.pipeline.analyze.ollama_client import call_llm

logger = logging.getLogger(__name__)


INDUSTRY_CODES = (
    "PHARMA, INSURANCE, OIL_GAS, DEFENSE, FINANCE, REAL_ESTATE, TECH, "
    "TELECOM, AGRIBUSINESS, ENERGY, CONSTRUCTION, TRANSPORT, LAWYERS, "
    "LOBBYISTS, GAMBLING, GUNS, TOBACCO, CRYPTO, PRIVATE_PRISON, OTHER"
)

POLICY_TAXONOMY = {
    "LABOR": "labor unions workers employment wages collective bargaining NLRB workforce rights minimum wage overtime",
    "DEFENSE": "military defense national security armed forces Pentagon troops veterans weapons procurement defense spending authorization",
    "GUNS": "firearms gun control second amendment weapons background checks ammunition assault weapons mass shootings",
    "HEALTHCARE": "healthcare medical insurance hospitals Medicare Medicaid public health drugs prescription ACA Affordable Care Act",
    "ENVIRONMENT": "environment climate change pollution EPA emissions regulations conservation clean air water endangered species carbon",
    "TAXES": "taxes tax reform revenue IRS deductions credits corporate tax income tax estate tax capital gains",
    "IMMIGRATION": "immigration border security asylum refugees visa DACA citizenship deportation undocumented",
    "EDUCATION": "education schools universities student loans teachers curriculum STEM federal education Pell grants Title I",
    "FINANCIAL": "financial regulation banking Wall Street SEC consumer protection Dodd-Frank CFPB banking oversight",
    "ENERGY": "energy renewable solar wind nuclear fossil fuel pipeline drilling electricity clean energy subsidies grid power plant",
    "TECH": "technology internet data privacy cybersecurity artificial intelligence social media antitrust big tech surveillance",
    "JUSTICE": "criminal justice police reform sentencing prison courts judicial system law enforcement bail mandatory minimum",
    "TRADE": "trade tariffs imports exports international commerce USMCA sanctions foreign trade China",
    "WELFARE": "welfare social programs food stamps SNAP housing assistance unemployment benefits poverty safety net",
    "PROCEDURAL": "nomination confirmation cloture procedural motion table resolution appointing executive calendar",
}

POLICY_AREAS = ", ".join(POLICY_TAXONOMY.keys())

PROCEDURAL_KEYWORDS = [
    "nomination", "confirming", "cloture", "motion to proceed",
    "motion to table", "motion to reconsider", "quorum",
    "adjourn", "reading of the journal", "appointment",
    "resolution of ratification", "executive calendar",
]

_policy_embeddings: dict[str, np.ndarray] = {}


def _get_policy_embeddings() -> dict[str, np.ndarray]:
    """Pre-compute embeddings for each policy area description."""
    if _policy_embeddings:
        return _policy_embeddings

    from app.pipeline.vector_store import get_embedding_model
    model = get_embedding_model()

    for area, description in POLICY_TAXONOMY.items():
        emb = model.encode([description], show_progress_bar=False)[0]
        _policy_embeddings[area] = emb / np.linalg.norm(emb)

    return _policy_embeddings


def classify_policy_area(text: str) -> tuple[str, float]:
    """Classify policy area via embedding cosine similarity.

    Returns:
        (policy_area, confidence) where confidence is the cosine similarity score.
    """
    if not text or len(text.strip()) < 5:
        return "PROCEDURAL", 0.0

    lower = text.lower()
    for kw in PROCEDURAL_KEYWORDS:
        if kw in lower:
            return "PROCEDURAL", 1.0

    from app.pipeline.vector_store import get_embedding_model
    model = get_embedding_model()
    policy_embs = _get_policy_embeddings()

    query_emb = model.encode([text[:500]], show_progress_bar=False)[0]
    query_emb = query_emb / np.linalg.norm(query_emb)

    best_area = "PROCEDURAL"
    best_score = 0.0

    for area, area_emb in policy_embs.items():
        score = float(np.dot(query_emb, area_emb))
        if score > best_score:
            best_score = score
            best_area = area

    return best_area, best_score


async def classify_all_bills(
    bills: list[dict], db_session: Any | None = None
) -> list[dict]:
    """Classify bills using hybrid approach: embeddings for policy area, LLM for reasoning.

    Bills classified as PROCEDURAL with high confidence skip the LLM entirely.
    Other bills get their policy area pre-classified, then the LLM provides
    stance, description, and impact analysis.
    """
    if not bills:
        return []

    logger.info("Classifying %d bills (hybrid: embeddings + LLM)...", len(bills))
    classified = []
    llm_skipped = 0

    for b in bills:
        summary = (b.get("summary") or b.get("billName", ""))[:300]
        bill_text = f"{b['billName']} {summary}"

        policy_area, confidence = classify_policy_area(bill_text)

        if policy_area == "PROCEDURAL" and confidence >= 0.8:
            classified.append({
                "billId": b["billId"],
                "billName": b["billName"],
                "congress": b["congress"],
                "date": "",
                "description": b["billName"],
                "policyArea": "PROCEDURAL",
                "stance": "procedural",
                "stanceVote": None,
                "impactedGroups": [],
                "corporateInterest": "",
                "publicImpact": "",
                "affectedIndustries": [],
                "partyLeaning": "bipartisan",
            })
            llm_skipped += 1
            continue

        result = await call_llm(
            prompt_version="bill-classify-v8",
            system_prompt="Congressional policy analyst. Return ONLY valid JSON.",
            user_prompt=f"""Classify this bill's stance and impact:
billId: {b['billId']}
billName: {b['billName']}
congress: {b['congress']}
policyArea: {policy_area}
summary: {summary}

The policy area has been pre-classified as {policy_area}. Focus on:
1. What specific STANCE does this bill take within {policy_area}?
2. Who is IMPACTED and how?

Return JSON:
{{"billId":"{b['billId']}","billName":"{b['billName']}","congress":{b['congress']},"date":"","description":"<1 sentence>","policyArea":"{policy_area}","stance":"<specific position within {policy_area}>","stanceVote":"Yea","impactedGroups":["<2-4 groups>"],"corporateInterest":"<1 sentence>","publicImpact":"<1 sentence>","affectedIndustries":["<1-3 codes from: {INDUSTRY_CODES}>"],"partyLeaning":"<R|D|bipartisan>"}}""",
            cache_key={"billId": b["billId"], "v": 8},
            db_session=db_session,
            max_tokens=350,
        )

        if result and isinstance(result, dict) and result.get("billId"):
            result["policyArea"] = policy_area
            classified.append(result)
        else:
            logger.warning("Bill classification failed for %s", b["billId"])

    _validate_classifications(classified)
    logger.info(
        "Classified %d/%d bills (%d procedural skipped LLM)",
        len(classified), len(bills), llm_skipped,
    )
    return classified


async def classify_recent_votes(
    roll_calls: list[dict], db_session: Any | None = None
) -> list[dict]:
    """Classify recent roll call votes using hybrid approach."""
    if not roll_calls:
        return []

    logger.info("Classifying %d recent votes (hybrid)...", len(roll_calls))
    classified = []
    llm_skipped = 0

    for rc in roll_calls:
        bill_id = rc.get("documentName") or f"Roll-{rc['rollNumber']}"
        name = rc.get("documentTitle") or rc.get("voteTitle") or "Unknown"
        question = (rc.get("question") or "")[:200]
        vote_date = rc.get("voteDate", "")

        vote_text = f"{name} {question}"
        policy_area, confidence = classify_policy_area(vote_text)

        if policy_area == "PROCEDURAL" and confidence >= 0.8:
            classified.append({
                "billId": bill_id,
                "billName": name,
                "date": vote_date,
                "description": name,
                "policyArea": "PROCEDURAL",
                "stance": "nomination" if "nominat" in vote_text.lower() else "procedural",
                "stanceVote": None,
                "impactedGroups": [],
                "corporateInterest": "",
                "publicImpact": "",
                "affectedIndustries": [],
                "partyLeaning": "bipartisan",
            })
            llm_skipped += 1
            continue

        result = await call_llm(
            prompt_version="recent-vote-classify-v5",
            system_prompt="Congressional policy analyst. Return ONLY valid JSON.",
            user_prompt=f"""Classify this Senate vote's stance and impact:
billId: {bill_id}
billName: {name}
date: {vote_date}
question: {question}
policyArea: {policy_area}

The policy area has been pre-classified as {policy_area}. Focus on:
1. What specific STANCE does this vote take within {policy_area}?
2. Who is IMPACTED?

Return JSON:
{{"billId":"{bill_id}","billName":"{name}","date":"{vote_date}","description":"<1 sentence>","policyArea":"{policy_area}","stance":"<specific position>","stanceVote":"Yea","impactedGroups":["<2-4 groups>"],"corporateInterest":"<1 sentence>","publicImpact":"<1 sentence>","affectedIndustries":["<codes>"],"partyLeaning":"<R|D|bipartisan>"}}""",
            cache_key={"billId": bill_id, "v": 5},
            db_session=db_session,
            max_tokens=350,
        )

        if result and isinstance(result, dict) and result.get("billId"):
            result["policyArea"] = policy_area
            classified.append(result)
        else:
            logger.warning("Recent vote classification failed for %s", bill_id)

    _validate_classifications(classified)
    logger.info(
        "Classified %d/%d recent votes (%d procedural skipped LLM)",
        len(classified), len(roll_calls), llm_skipped,
    )
    return classified


def _validate_classifications(bills: list[dict]) -> None:
    """Validate and fix classification fields in-place."""
    for bill in bills:
        if not bill.get("policyArea") or not isinstance(bill.get("policyArea"), str):
            bill["policyArea"] = "PROCEDURAL"
        bill["policyArea"] = bill["policyArea"].strip().upper()

        if not bill.get("stance") or not isinstance(bill.get("stance"), str):
            bill["stance"] = "neutral"
        bill["stance"] = bill["stance"].strip().lower()

        if bill.get("stanceVote") not in ("Yea", "Nay"):
            bill["stanceVote"] = None

        if not isinstance(bill.get("impactedGroups"), list):
            bill["impactedGroups"] = []

        if bill.get("partyLeaning") not in ("R", "D", "bipartisan"):
            bill["partyLeaning"] = "bipartisan"
