"""Periodic Bluesky posts: daily senator score spotlight + weekly civic summary.

Senator spotlight: once per day, picks a senator who hasn't been spotlighted
yet (cycling through all before repeating) and posts a score highlight.

Weekly summary: once per week, posts a condensed version of the week-in-review
summary generated by the timeline pipeline.
"""

import logging
import random
import re
from datetime import datetime, UTC

from sqlalchemy.orm import Session

from app.config import settings
from app.models import BskySenatorSpotlight, Senator, WeekSummary
from app.pipeline.analyze.bluesky_utils import build_link_card
from app.pipeline.analyze.grounding import (
    hedge_and_editorializing_violations,
    ungrounded_numbers,
)
from app.pipeline.analyze.ollama_client import call_llm
from app.pipeline.analyze.score_calculator import compute_overall_score

logger = logging.getLogger(__name__)

MAX_SPOTLIGHT_CHARS = 240
SITE = "https://civitas-research.org"

_SYSTEM_PROMPT = (
    "You are a nonpartisan civic journalist writing brief, factual posts for "
    "the Civitas transparency platform. Civitas scores U.S. senators on "
    "funding independence, independent voting, funding diversity, and "
    "legislative effectiveness. Your posts are data-driven, "
    "neutral, and written to help citizens understand how their representatives "
    "are performing."
)


def _pick_senator(db: Session) -> tuple["Senator | None", int, int]:
    """Return (senator, rank, total), picked uniformly at random from senators
    not yet spotlighted this cycle (cycling through all before repeating).

    Deliberately NOT biased toward the highest or lowest scorer: always
    picking an extreme, combined with the LLM being told to frame it as
    praise or criticism, produced a real incident — a "praise" post about a
    senator's score read as badly out of touch after negative news broke
    about him the same day. A random pick with objective, unevaluative
    framing (see _generate_spotlight_post) can't have the same failure mode.
    """
    spotlighted_ids = {
        row.senator_id
        for row in db.query(BskySenatorSpotlight.senator_id).all()
    }

    senators = (
        db.query(Senator)
        .filter(Senator.score_funding_independence.isnot(None))
        .filter(Senator.is_current.is_(True))
        .all()
    )
    if not senators:
        return None, 0, 0

    # All senators ranked best → worst (for absolute rank lookup)
    all_ranked = sorted(senators, key=compute_overall_score, reverse=True)
    total = len(all_ranked)

    unspotlighted = [s for s in all_ranked if s.id not in spotlighted_ids]
    if not unspotlighted:
        logger.info("All %d senators spotlighted — resetting cycle", total)
        db.query(BskySenatorSpotlight).delete()
        db.commit()
        unspotlighted = list(all_ranked)

    pick = random.choice(unspotlighted)

    rank = next(i + 1 for i, s in enumerate(all_ranked) if s.id == pick.id)
    return pick, rank, total


# Deviation from the neutral midpoint (50) required before a dimension is
# worth singling out by name at all. Below this band a score is unremarkable
# no matter which of the five dimensions happens to be furthest from 50: with
# Promise Persistence's shrinkage prior compressing most senators into the
# low-to-mid 50s (2026-07 audit), the *least-bad* of five middling scores
# was still being singled out ("Her highest score is Promise Persistence at
# 55.0/100" — for a senator ranked 98th of 100). Picking the dimension to
# mention server-side, instead of leaving the choice to the model, removes
# that ambiguity. This is purely about which number gets named — every post,
# notable dimension or not, must still state it as a plain fact (see
# _EMPHASIS_WORDS below, checked unconditionally).
_NOTABLE_DEVIATION = 20

# Evaluative language is banned outright, not just for unremarkable scores —
# posts state numbers as facts and let the reader judge. (A "praise" post
# about a senator's high score read as badly out of touch after negative
# news broke about him hours later; there is no framing that's safe to
# automate, so the fix is not to editorialize at all, ever.)
_EMPHASIS_WORDS = (
    "standout", "impressive", "excel", "shine", "notably", "particularly",
    "remarkable", "exceptional", "outstanding", "strong commitment",
    "effectively", "noteworthy", "concerning", "worrying", "troubling",
    "praiseworthy", "commendable", "questionable", "admirable",
    "disappointing", "impress",
)


def _most_notable_score(scores: dict[str, float]) -> tuple[str, float, bool]:
    """The dimension furthest from neutral, and whether it's actually notable."""
    key = max(scores, key=lambda k: abs(scores[k] - 50))
    value = scores[key]
    return key, value, abs(value - 50) >= _NOTABLE_DEVIATION


def _generate_spotlight_post(senator: "Senator", rank: int, total: int) -> str | None:
    """Ask the LLM to write a score highlight post for this senator."""
    scores = {
        "Funding independence": round(senator.score_funding_independence or 0, 1),
        "Independent voting": round(senator.score_independent_voting or 0, 1),
        "Funding diversity": round(senator.score_funding_diversity or 0, 1),
        "Legislative effectiveness": round(senator.score_legislative_effectiveness or 0, 1),
    }
    # The posted overall must be the same weighted composite the site shows
    # (SCORE_WEIGHTS) — a plain mean of the five dimensions published a
    # different number than the leaderboard for every senator.
    overall = round(compute_overall_score(senator), 1)
    score_lines = "\n".join(f"- {k}: {v}/100" for k, v in scores.items())

    # Rank is stated plainly — never characterized as an achievement or a
    # failure. See module-level note on _pick_senator for why.
    standing = f"ranks #{rank} of {total} senators"

    notable_key, notable_value, is_notable = _most_notable_score(scores)
    if is_notable:
        highlight_instruction = (
            f"2. Name {notable_key} ({notable_value}/100) — it is the score furthest from the "
            f"neutral midpoint (50) for this senator. State the number as a plain fact. Do not "
            f"say it is good, bad, high, low, strong, or weak — just report it."
        )
    else:
        highlight_instruction = (
            "2. None of the five individual scores is unusually far from the neutral midpoint "
            "(50) — they all sit in the ordinary range. Do NOT single out any one dimension. "
            "State the overall score and rank plainly."
        )

    user_prompt = f"""Write a Bluesky post spotlighting this senator's Civitas transparency score.

Senator: {senator.name} ({senator.party}-{senator.state})
Overall score: {overall}/100 ({standing})
Individual scores:
{score_lines}

RULES:
1. Mention the senator's name, state, and their overall score and rank.
{highlight_instruction}
3. State every number as a neutral fact. Do not praise, criticize, or use any evaluative
   language — no "good", "bad", "strong", "weak", "impressive", "concerning", or similar.
   This is a report, not a review: let the reader draw their own conclusion from the numbers.
4. STRICT MAXIMUM: {MAX_SPOTLIGHT_CHARS} characters total.
5. Write 1-2 complete sentences ending with proper punctuation.
6. No hashtags, no exclamation points, no editorializing.
7. Do not add any information not provided above.
8. Report directly — never write "sources show," "reports indicate," or similar.
   State the scores as facts, not as something reports/coverage/sources are saying.

Return JSON: {{"post": "<your post text>"}}"""

    retry_note = ""
    for attempt in range(2):
        result = call_llm(
            prompt_version="bsky_spotlight_v2",
            system_prompt=_SYSTEM_PROMPT,
            user_prompt=user_prompt + retry_note,
            cache_key=None,
            db_session=None,
            max_tokens=200,
            num_ctx=1024,
        )
        if not result or not isinstance(result.get("post"), str):
            return None

        text = re.sub(r"#(\w+)", r"\1", result["post"]).strip()
        if len(text) > MAX_SPOTLIGHT_CHARS:
            trimmed = text[:MAX_SPOTLIGHT_CHARS]
            cut = max(
                (trimmed.rfind(p) + 1 for p in (".", "!", "?") if trimmed.rfind(p) > 0),
                default=-1,
            )
            text = trimmed[:cut] if cut > 0 else trimmed[: trimmed.rfind(" ")]
        text = text.strip()

        problems = []

        # Scores publish publicly under the platform's name: every number in
        # the post must be one we actually supplied (a score, the rank, or
        # the senator count). A mangled or invented figure is worse than no
        # post — skip after one corrective retry.
        novel = ungrounded_numbers(text, user_prompt)
        if novel:
            problems.append(f"numbers not provided above ({', '.join(novel)})")

        # Every post must be a neutral report, not a review — no praise or
        # criticism of any score, notable or not. See _EMPHASIS_WORDS.
        lower = text.lower()
        hit = next((w for w in _EMPHASIS_WORDS if w in lower), None)
        if hit:
            problems.append(f'evaluative language ("{hit}") — posts must stay neutral')

        # Same mechanical backstop as the issue poster and full-story
        # generator — prompt-only instructions aren't reliably followed.
        problems += hedge_and_editorializing_violations(text)

        if not problems:
            return text
        logger.warning(
            "Spotlight post rejected for %s (attempt %d): %s | post: %s",
            senator.name, attempt + 1, "; ".join(problems), text[:160],
        )
        retry_note = (
            "\n\nYour previous attempt was rejected because it contained "
            f"{' and '.join(problems)}. Use only the scores and ranking "
            "given, and keep the tone plain when no score stands out."
        )

    return None




def _publish_spotlight(text: str, senator: Senator) -> bool:
    """Post the spotlight to Bluesky. Returns True on success."""
    handle = getattr(settings, "BSKY_HANDLE", "")
    app_password = getattr(settings, "BSKY_APP_PASSWORD", "")
    if not handle or not app_password:
        return False

    url = f"{SITE}/politicians/{senator.id}"
    full_text = f"{text}\n\n{url}"

    if len(full_text) > 300:
        budget = 300 - len(url) - 2
        trimmed = text[:budget]
        cut = max(
            (trimmed.rfind(p) + 1 for p in (".", "!", "?") if trimmed.rfind(p) > 0),
            default=-1,
        )
        trimmed = trimmed[:cut] if cut > 0 else trimmed[: trimmed.rfind(" ")]
        full_text = f"{trimmed}\n\n{url}"

    try:
        from atproto import Client, models

        client = Client()
        client.login(handle, app_password)

        encoded = full_text.encode("utf-8")
        url_bytes = url.encode("utf-8")
        url_start = encoded.find(url_bytes)
        facets = [
            models.AppBskyRichtextFacet.Main(
                features=[models.AppBskyRichtextFacet.Link(uri=url)],
                index=models.AppBskyRichtextFacet.ByteSlice(
                    byte_start=url_start,
                    byte_end=url_start + len(url_bytes),
                ),
            )
        ]
        embed = build_link_card(client, url)
        client.send_post(full_text, facets=facets, embed=embed)
        logger.info("Posted senator spotlight: %s", senator.name)
        return True
    except ImportError:
        logger.error("atproto not installed — cannot post spotlight")
        return False
    except Exception:
        logger.exception("Spotlight post failed for senator %s", senator.id)
        return False


def post_daily_spotlight(db: Session) -> None:
    """Post a daily senator score spotlight. No-op if already posted today."""
    if not getattr(settings, "BSKY_HANDLE", "") or not getattr(settings, "BSKY_APP_PASSWORD", ""):
        return

    today = datetime.now(UTC).date().isoformat()
    already_posted = (
        db.query(BskySenatorSpotlight)
        .filter(BskySenatorSpotlight.posted_at >= today)
        .first()
    )
    if already_posted:
        logger.debug("Spotlight already posted today — skipping")
        return

    senator, rank, total = _pick_senator(db)
    if not senator:
        logger.warning("No senators available for spotlight")
        return

    text = _generate_spotlight_post(senator, rank, total)
    if not text:
        logger.warning("Failed to generate spotlight text for %s", senator.name)
        return

    if _publish_spotlight(text, senator):
        db.add(BskySenatorSpotlight(
            senator_id=senator.id,
            posted_at=datetime.now(UTC),
            post_text=text,
        ))
        db.commit()
        logger.info("Senator spotlight posted: %s", senator.name)


TIMELINE_URL = f"{SITE}/timeline"
MAX_WEEKLY_CHARS = 240


def _generate_weekly_post(week: WeekSummary) -> str | None:
    """Condense the week-in-review summary into a Bluesky post."""
    monday = week.start_date  # YYYY-MM-DD
    sunday = week.end_date
    try:
        from datetime import date
        label = f"{date.fromisoformat(monday).strftime('%b %-d')}–{date.fromisoformat(sunday).strftime('%-d')}"
    except Exception:
        label = f"{monday} – {sunday}"

    user_prompt = f"""Write a Bluesky post summarizing this week in civic news for Civitas.

Week: {label}
Week-in-review summary:
{week.summary[:800]}

RULES:
1. 2-3 sentences maximum.
2. STRICT MAXIMUM: {MAX_WEEKLY_CHARS} characters total.
3. Mention 2-3 of the most significant specific events or developments from the week.
4. No hashtags, no exclamation points, no editorializing.
5. Factual and neutral — report what happened.
6. Do not start with "This week" or "Last week".
7. Report directly — never write "sources show," "reports indicate," or similar.
   State events as facts, not as something reports/coverage/sources are saying.
8. Do not evaluate whether an action was warranted or justified, and do not
   speculate about its political purpose or effect.

Return JSON: {{"post": "<your post text>"}}"""

    retry_note = ""
    for attempt in range(2):
        result = call_llm(
            prompt_version="bsky_weekly_v1",
            system_prompt=_SYSTEM_PROMPT,
            user_prompt=user_prompt + retry_note,
            cache_key=None,
            db_session=None,
            max_tokens=200,
            num_ctx=2048,
        )
        if not result or not isinstance(result.get("post"), str):
            return None

        text = re.sub(r"#(\w+)", r"\1", result["post"]).strip()
        if len(text) > MAX_WEEKLY_CHARS:
            trimmed = text[:MAX_WEEKLY_CHARS]
            cut = max(
                (trimmed.rfind(p) + 1 for p in (".", "!", "?") if trimmed.rfind(p) > 0),
                default=-1,
            )
            text = trimmed[:cut] if cut > 0 else trimmed[: trimmed.rfind(" ")]
        text = text.strip()
        if not text:
            return None

        # Same public-post guard as the spotlight: every number must come
        # from the week summary (or the date label) we supplied. Hedging
        # attribution and editorializing get the same mechanical backstop
        # as the issue poster and full-story generator.
        reasons = []
        novel = ungrounded_numbers(text, user_prompt)
        if novel:
            reasons.append(f"numbers not present in the summary ({', '.join(novel)})")
        reasons += hedge_and_editorializing_violations(text)
        if not reasons:
            return text

        logger.warning(
            "Weekly post failed grounding (attempt %d): %s | post: %s",
            attempt + 1, "; ".join(reasons), text[:160],
        )
        retry_note = (
            "\n\nYour previous attempt was rejected because it contained "
            f"{'; '.join(reasons)}. Use only figures from the week-in-review "
            "summary above, report events directly instead of through "
            "phrases like 'sources show' or 'reports indicate,' and do not "
            "evaluate whether any action was warranted or justified."
        )

    return None


def _publish_weekly(text: str, week: WeekSummary) -> bool:
    """Post the weekly summary to Bluesky. Returns True on success."""
    handle = getattr(settings, "BSKY_HANDLE", "")
    app_password = getattr(settings, "BSKY_APP_PASSWORD", "")
    if not handle or not app_password:
        return False

    full_text = f"{text}\n\n{TIMELINE_URL}"
    if len(full_text) > 300:
        budget = 300 - len(TIMELINE_URL) - 2
        trimmed = text[:budget]
        cut = max(
            (trimmed.rfind(p) + 1 for p in (".", "!", "?") if trimmed.rfind(p) > 0),
            default=-1,
        )
        trimmed = trimmed[:cut] if cut > 0 else trimmed[: trimmed.rfind(" ")]
        full_text = f"{trimmed}\n\n{TIMELINE_URL}"

    try:
        from atproto import Client, models

        client = Client()
        client.login(handle, app_password)

        encoded = full_text.encode("utf-8")
        url_bytes = TIMELINE_URL.encode("utf-8")
        url_start = encoded.find(url_bytes)
        facets = [
            models.AppBskyRichtextFacet.Main(
                features=[models.AppBskyRichtextFacet.Link(uri=TIMELINE_URL)],
                index=models.AppBskyRichtextFacet.ByteSlice(
                    byte_start=url_start,
                    byte_end=url_start + len(url_bytes),
                ),
            )
        ]
        embed = build_link_card(client, TIMELINE_URL)
        client.send_post(full_text, facets=facets, embed=embed)
        logger.info("Posted weekly summary for week %d/%d", week.year, week.week_num)
        return True
    except ImportError:
        logger.error("atproto not installed — cannot post weekly summary")
        return False
    except Exception:
        logger.exception("Weekly summary post failed for week %d/%d", week.year, week.week_num)
        return False


def post_weekly_summary(db: Session) -> None:
    """Post the most recently completed week-in-review, at most once per week.

    Older unposted weeks are silently marked as skipped so a backlog of
    unposted summaries doesn't fire in rapid succession after a deployment.
    """
    if not getattr(settings, "BSKY_HANDLE", "") or not getattr(settings, "BSKY_APP_PASSWORD", ""):
        return

    from datetime import timedelta

    # Enforce a 6-day cooldown — prevents hourly pipeline from posting
    # multiple backlogged weeks in the same day.
    last_posted = (
        db.query(WeekSummary)
        .filter(WeekSummary.bsky_posted_at.isnot(None))
        .order_by(WeekSummary.bsky_posted_at.desc())
        .first()
    )
    if last_posted and last_posted.bsky_posted_at:
        age = datetime.now(UTC) - last_posted.bsky_posted_at.replace(tzinfo=UTC)
        if age < timedelta(days=6):
            logger.debug("Weekly summary posted %d days ago — skipping", age.days)
            return

    unposted = (
        db.query(WeekSummary)
        .filter(WeekSummary.bsky_posted_at.is_(None))
        .order_by(WeekSummary.end_date.desc())
        .all()
    )
    if not unposted:
        return

    # Post only the most recent unposted week; mark the rest as skipped
    week = unposted[0]
    skipped = unposted[1:]
    if skipped:
        for w in skipped:
            w.bsky_posted_at = datetime.now(UTC)  # mark skipped so they don't queue up
        db.commit()
        logger.info("Marked %d stale week summaries as skipped", len(skipped))

    text = _generate_weekly_post(week)
    if not text:
        logger.warning("Failed to generate weekly summary post for week %d/%d", week.year, week.week_num)
        return

    if _publish_weekly(text, week):
        week.bsky_posted_at = datetime.now(UTC)
        db.commit()
        logger.info("Weekly summary posted for %s–%s", week.start_date, week.end_date)
