"""Which bills a lobbying filing names, and whether a named bill is the one
a member voted on.

A Lobbying Disclosure Act report lists, per issue area, the specific
legislation the registrant lobbied on, in the filer's own free text
("H.R. 1492, to equalize the negotiation period ..."; "S 526 - Pharmacy
Benefit Manager Transparency Act of 2025"). That text is the only per-bill
record the LDA publishes, and it is the difference between "this donor's
industry overlaps this vote's topic" and "this donor's own lobbying filing
names the bill this member voted on".

Measured on 3,175 activity descriptions from 2025 filings by 48 large
clients (scripts/calibrate_lda_bill_match.py reproduces every number here),
four facts about the text decide the design:

1. **Filers don't use the Congressional Record's spelling.** 267 of 3,846
   bill references were written without periods ("HR 1062", "S 933",
   "HR1078"). The Record's own parser (daily_digest._MEASURE_RE) requires
   the periods, and must: in the Record, "S4897" is a page reference.
   Filings have no page references, so the pattern here accepts both.

2. **A number alone doesn't identify a bill.** Filings in 2025 still cite
   118th-Congress bills by number ("S 4921/HR 8774 - Department of Defense
   Appropriations Act, 2025"), and H.R. 8774 in the 119th is a different
   bill. So a number counts only when the filer's words name the bill:
   `title_match_score` must reach BILL_TITLE_MATCH_MIN against one of its
   current-congress titles. Of 2,530 mentions of current-congress numbers,
   the fit is bimodal — 1,267 at 1.0, 973 under 0.2.

3. **A fitting title can still be a sibling's.** Appropriations acts and
   Congressional Review Act resolutions share all but a word or two of
   their titles: a filing about the Defense appropriations act, citing the
   Education act's number, fits the Education act at 0.72; one about the
   rubber-tire emissions rule fits the waste-emissions-charge resolution at
   0.61. So the number counts only when no other bill of the congress
   (`TitlePool`) fits the words better by more than RIVAL_TOLERANCE, and
   the previous congress's bill with the same number doesn't fit them
   better either (a 2025 filing's "H.R. 82 - Social Security Fairness Act"
   is the 118th's H.R. 82). 1,349 mentions clear the fit threshold and
   1,295 survive these checks; the ones read by hand after them were the
   right bill, except that a Review Act resolution's number can't always be
   told from the text alone. Correct bills lost by a margin over the
   tolerance are dropped (H.R. 1492 against the Inflation Reduction Act
   named in the same clause, at 0.10): a missing link costs less than a
   link to the wrong bill.

4. **The title belongs next to its number.** Filers write it after
   ("S 526 - Pharmacy Benefit ...") or before ("... Act (H.R. 2854)"), in
   lists; `bill_mentions` keeps each side separately, from the number to the
   neighbouring number or the end of the clause, and each side is judged on
   its own.

The fit weights each title word by its rarity across all bill titles
(inverse document frequency over the 118th and 119th congresses' titles,
`app/data/bill_title_token_df.json`, generated by the calibration script):
without it, "Act of" carries a large share of a short title's words, and an
early version of this sample gave 28 false matches at the threshold. Words
match with Ratcliff/Obershelp similarity >= 0.8, so filers' typos ("Whole
Homes Repairs Act", "Stopping Pharmas Ripoffs") still count.

Nothing here decides a donor's position on a bill. A filing says the client
lobbied on it, not for or against it — the LDA form has no such field.
"""

from __future__ import annotations

import json
import logging
import math
import pathlib
import re
from difflib import SequenceMatcher
from functools import lru_cache

logger = logging.getLogger(__name__)

# Measured on the calibration sample (module docstring): below it the
# wrong-bill cases begin (a filing naming "Securing Access to Care for Seniors
# in Critical Condition Act" beside S.1816's number fits S.1816's real title
# at 0.56).
BILL_TITLE_MATCH_MIN = 0.6

# How far another bill's title may out-fit this bill's before it wins. Measured
# (module docstring): companion bills and filers' spellings differ by a filler
# word ("CONNECT for Health Act" vs "... Act of 2025") and trail by 0.05 or
# less; the first wrong-bill cases trail by 0.08 (sibling review-act
# resolutions) and 0.10 (the rubber-tire rule's resolution scored against the
# waste-emissions one).
RIVAL_TOLERANCE = 0.05

# A typo-tolerant word match (Ratcliff & Obershelp 1988), and how far apart
# two words' lengths may be before the comparison is skipped as pointless.
_WORD_SIMILARITY_MIN = 0.8
_WORD_LENGTH_SLACK = 3

# Context kept on each side of a bill number: the filer's title for it
# usually sits right after the number, sometimes before it
# ("... Neighborhood Homes Investment Act (H.R.2854/S.1686)").
CONTEXT_CHARS = 200

# The filer's spellings -> the site's bill-id prefix. Order matters: the
# longer forms must be tried before "H.R."/"S." swallow their first letters.
# Case: the chamber letters are written upper-case in every filing sampled,
# and requiring it keeps "items 5"-style prose out; the rest is either case.
_MEASURE_TYPES: tuple[tuple[str, str], ...] = (
    (r"H\.?\s?(?i:con)\.?\s?(?i:res)\.?", "HCONRES"),
    (r"S\.?\s?(?i:con)\.?\s?(?i:res)\.?", "SCONRES"),
    (r"H\.?\s?J\.?\s?(?i:res)\.?", "HJRES"),
    (r"S\.?\s?J\.?\s?(?i:res)\.?", "SJRES"),
    (r"H\.?\s?(?i:res)\.?", "HRES"),
    (r"S\.?\s?(?i:res)\.?", "SRES"),
    (r"H\.?\s?R\.?", "HR"),
    (r"S\.?", "S"),
)
_MEASURE_RE = re.compile(
    r"(?<![A-Za-z0-9.])(?:"
    + "|".join(f"(?P<t{i}>{p})" for i, (p, _) in enumerate(_MEASURE_TYPES))
    + r")\s?(?P<n>\d{1,5})\b"
)

_TOKEN_RE = re.compile(r"[a-z0-9]+")
_YEAR_RE = re.compile(r"(?:19|20)\d\d")

_DF_PATH = pathlib.Path(__file__).resolve().parents[2] / "data" / "bill_title_token_df.json"


# Where a filer's clause ends: a semicolon, a line break, or a sentence
# end — a period after a real word (two or more lower-case letters), so an
# initial ("Richard L. Trumka") or "U.S." doesn't end one.
_CLAUSE_END_RE = re.compile(r";|\n|(?<=[a-z]{2})\.\s+(?=[A-Z])")


def bill_mentions(text: str) -> list[tuple[str, str, str]]:
    """Every bill or resolution number in a filing's text, as (site bill id,
    the filer's words before it, the filer's words after it).

    Each side stops at the neighbouring bill number or the end of the
    clause, and is capped at CONTEXT_CHARS. Filers write a bill's title
    after its number ("S 526 - Pharmacy Benefit ...") or before it ("...
    Homes Investment Act (H.R.2854)"); the two sides are kept apart so the
    title that belongs to a neighbouring number in a list is not read as
    this one's (names_bill tests each side on its own).
    """
    text = text or ""
    matches = list(_MEASURE_RE.finditer(text))
    out: list[tuple[str, str, str]] = []
    for k, m in enumerate(matches):
        prefix = next(
            _MEASURE_TYPES[i][1] for i in range(len(_MEASURE_TYPES)) if m.group(f"t{i}")
        )
        lo = matches[k - 1].end() if k else 0
        hi = matches[k + 1].start() if k + 1 < len(matches) else len(text)
        after = text[m.end():hi]
        end = _CLAUSE_END_RE.search(after)
        after = after[: end.start()] if end else after
        before = text[lo:m.start()]
        starts = list(_CLAUSE_END_RE.finditer(before))
        before = before[starts[-1].end():] if starts else before
        out.append((
            f"{prefix}.{int(m.group('n'))}",
            before[-CONTEXT_CHARS:],
            after[:CONTEXT_CHARS],
        ))
    return out


def _tokens(text: str, years: bool = False) -> set[str]:
    """Title words: letters-and-digits runs of two or more characters.
    Numbers are dropped; with `years`, a year is kept. Years tell a
    reintroduced bill ("... Act of 2025") from the previous congress's ("...
    Act of 2023"), and nothing else: within a congress, a companion bill's
    title can differ from its twin's by the year alone, and filers mostly
    leave the year out, so counting it would let the twin without one win."""
    return {
        t for t in _TOKEN_RE.findall((text or "").lower())
        if len(t) >= 2 and (not t.isdigit() or (years and _YEAR_RE.fullmatch(t)))
    }


@lru_cache(maxsize=1)
def _document_frequencies() -> tuple[int, dict[str, int]]:
    """(number of titles, per-word title counts) from the generated table.
    Words seen in only one title are not stored and count as 1."""
    data = json.loads(_DF_PATH.read_text())
    return int(data["documents"]), {k: int(v) for k, v in data["df"].items()}


def _idf(token: str) -> float:
    n, df = _document_frequencies()
    return math.log(n / (1 + df.get(token, 1)))


def _word_found(word: str, context_words: set[str]) -> bool:
    if word in context_words:
        return True
    return any(
        abs(len(word) - len(w)) <= _WORD_LENGTH_SLACK
        and SequenceMatcher(None, word, w).ratio() >= _WORD_SIMILARITY_MIN
        for w in context_words
    )


def title_match_score(context: str, titles: list[str], years: bool = False) -> float:
    """How fully the filer's context contains one of the bill's titles:
    the rarity-weighted share of the title's words found in it, best title
    wins. 0.0 when there are no titles to compare. `years`: see _tokens."""
    context_words = _tokens(context, years)
    best = 0.0
    for title in titles:
        words = _tokens(title, years)
        if not words:
            continue
        weights = {w: max(_idf(w), 0.0) for w in words}
        total = sum(weights.values())
        if total <= 0:
            continue
        found = sum(weight for w, weight in weights.items() if _word_found(w, context_words))
        best = max(best, found / total)
    return best


# Words shared by more titles than this don't nominate rival bills: "act",
# "amend", "united", "states" would make every bill a rival of every other.
_RIVAL_WORD_MAX_DF = 2000
# Rivals given the full (typo-tolerant) fit, best exact-word fit first. The
# exact fit is a few set operations per title; the full one runs
# SequenceMatcher per word pair. On the calibration sample, 30 agrees with
# scoring every rival on all but 2 of 2,530 mentions (one Review Act
# resolution whose winning rival wins only through a misspelling), at 4 ms
# a check instead of 120 ms; 60 and 100 disagree on the same 2.
_MAX_RIVALS = 30


class TitlePool:
    """Every bill of a congress, indexed by title word, to find the bill whose
    title best fits a filer's wording.

    A title that fits is not enough on its own: appropriations bills and
    Congressional Review Act resolutions share all but one or two of their
    title words with their siblings ("Department of Defense Appropriations
    Act, 2026" vs "Department of Education Appropriations Act, 2026"), so a
    filing about one clears any fixed threshold against the other's number.
    The number counts only when its own bill fits the wording about as well
    as any rival does (names_bill).
    """

    def __init__(self, titles: dict[str, list[str]]):
        self._titles = titles
        self._index: dict[str, set[str]] = {}
        # Per title: its words' rarity weights and their total, so a rival's
        # exact-word fit is a lookup rather than a rescoring.
        self._weights: dict[str, list[tuple[dict[str, float], float]]] = {}
        for bill_id, ts in titles.items():
            entries = []
            for t in ts:
                words = _tokens(t)
                weights = {w: max(_idf(w), 0.0) for w in words}
                entries.append((weights, sum(weights.values())))
                for w in words:
                    self._index.setdefault(w, set()).add(bill_id)
            self._weights[bill_id] = entries

    def _exact_fit(self, bill_id: str, context_words: set[str]) -> float:
        return max(
            (sum(v for w, v in weights.items() if w in context_words) / total
             for weights, total in self._weights[bill_id] if total > 0),
            default=0.0,
        )

    def best_rival_score(self, context: str, bill_id: str) -> float:
        """The best title fit among bills other than `bill_id`."""
        _, df = _document_frequencies()
        context_words = _tokens(context)
        rivals: set[str] = set()
        for w in context_words:
            if df.get(w, 1) <= _RIVAL_WORD_MAX_DF:
                rivals |= self._index.get(w, set())
        rivals.discard(bill_id)
        ranked = sorted(rivals, key=lambda b: self._exact_fit(b, context_words), reverse=True)
        return max(
            (title_match_score(context, self._titles[b]) for b in ranked[:_MAX_RIVALS]),
            default=0.0,
        )


def names_bill(
    before: str,
    after: str,
    titles: list[str],
    bill_id: str,
    pool: TitlePool | None,
    previous_titles: list[str] | None = None,
    fits: tuple[float, float] | None = None,
) -> bool:
    """Whether the filer's words on one side of a bill number name that bill.

    A side names it when the bill's titles fit it at least
    BILL_TITLE_MATCH_MIN and no other bill of the congress fits it better by
    more than RIVAL_TOLERANCE (companion bills in the two chambers share a
    title, give or take a word).
    The previous congress's bill with the same number is checked first, side
    by side: 2025 filings still cite the 118th Congress's H.R. 82 (the Social
    Security Fairness Act) as "H.R. 82", and when either side of the number
    fits that bill better than the current one, the filer meant the old
    bill — even if the other side, a neighbour's title in a list, happens to
    fit the current H.R. 82.

    `fits`: the (after, before) title fits, when the caller already has them.
    """
    sides = (after, before)
    if previous_titles:
        for side in sides:
            old = title_match_score(side, previous_titles, years=True)
            if old >= BILL_TITLE_MATCH_MIN and old > title_match_score(side, titles, years=True):
                # The filer titled this number with the earlier bill's name;
                # the other side, if it fits, is a neighbour's title.
                return False
    scores = fits or (title_match_score(after, titles), title_match_score(before, titles))
    for side, score in zip(sides, scores):
        if score < BILL_TITLE_MATCH_MIN:
            continue
        if pool is not None and score + RIVAL_TOLERANCE < pool.best_rival_score(side, bill_id):
            continue
        return True
    return False
