"""Per-chamber population references the pipeline measures every run.

Several scoring components compare a member against their chamber's own
population — the median member's bill credit (Legislative Effectiveness),
the median member's PAC share (Funding Independence), the break rate
same-party members show at each seat lean (Constituent Alignment). Those reference
values used to be Python literals pasted from a calibration script's
output (AGENTS.md §3a), which drift as the population changes. Instead the
pipeline measures each one from the members it is about to score, passes it
to calculate_scores, and persists it here so readers outside the run (the
API's on-demand score breakdowns, scripts/rescore.py) reproduce the
pipeline's numbers.

Each reference has two files:
  - /data/<name>.json — the last run's values, per chamber (the app's
    writable volume; app/data/ is baked into the image read-only — a
    pipeline-time write there crashed a production run on 2026-07-21);
  - app/data/<name>.json — a bundled fallback for before a deployment's
    first run, regenerated by the script its `_source` names.
"""

import logging
import pathlib

from app.atomic_write import update_json_file
from app.file_cache import Stamp, Uncached, read_json, reload_if_moved
from app.config_definitions import CONSTITUENT_REFERENCE_STATISTIC
from app.time_utils import utcnow

logger = logging.getLogger(__name__)

_BUNDLED_DIR = pathlib.Path(__file__).resolve().parent.parent.parent / "data"
_LIVE_DIR = pathlib.Path("/data")
CHAMBERS = ("senate", "house")


def _read_json(path: pathlib.Path) -> dict:
    """The file's JSON object; {} when it is missing or not one. Raises
    OSError when it exists but can't be read (file_cache.read_json)."""
    data = read_json(path)
    return data if isinstance(data, dict) else {}


class ChamberReference:
    """One named reference, one entry per population key — by default
    {"senate": {...}, "house": {...}}; the presidential reference has the
    single key "presidents"."""

    def __init__(self, name: str, keys: tuple[str, ...] = CHAMBERS, statistic: str | None = None):
        self.name = name
        self.keys = keys
        # When set, a per-chamber entry counts only if its "statistic" field
        # equals this: a reference measured on a different statistic (left
        # on /data by an older release) is skipped, falling back to the
        # bundled entry, rather than scored against on the wrong scale.
        self._statistic = statistic
        self.live_path = _LIVE_DIR / f"{name}.json"
        self.bundled_path = _BUNDLED_DIR / f"{name}.json"
        self._cache: dict | None = None
        self._cache_stamp: Stamp = None
        self._warned: set[tuple[str, str, str | None]] = set()

    @property
    def statistic(self) -> str | None:
        """Fixed at construction: which stored entries load() accepts."""
        return self._statistic

    def usable(self, entry: dict | None) -> bool:
        """Whether one chamber's entry can be scored against."""
        return (
            isinstance(entry, dict) and bool(entry)
            and (self.statistic is None or entry.get("statistic") == self.statistic)
        )

    def load(self) -> dict:
        """The live file layered over the bundled fallback, per chamber.
        Re-read whenever either file changes on disk (mtime), so the API
        worker that didn't run the pipeline doesn't keep serving the
        previous run's numbers."""
        self._cache, self._cache_stamp = reload_if_moved(
            [self.live_path, self.bundled_path], self._cache, self._cache_stamp, self._read,
        )
        return self._cache

    def _read(self) -> dict:
        unreadable = False
        files = {}
        for source, path in (("bundled", self.bundled_path), ("live", self.live_path)):
            try:
                files[source] = _read_json(path)
            except OSError:
                logger.warning("Couldn't read %s — retrying on next use", path, exc_info=True)
                files[source], unreadable = {}, True
        bundled, live = files["bundled"], files["live"]
        merged = {}
        for k in self.keys:
            for source, entry in (("live", live.get(k)), ("bundled", bundled.get(k))):
                if self.usable(entry):
                    merged[k] = entry
                    break
                warn_key = (source, k, entry.get("statistic") if isinstance(entry, dict) else repr(entry)[:40])
                if entry and warn_key not in self._warned:
                    # Once per stale entry per process: a chamber write
                    # re-reads the file, and the other chamber's stale entry
                    # is expected until its own run replaces it.
                    self._warned.add(warn_key)
                    logger.warning(
                        "Skipping the %s %s entry for %s: measured on %r, not %r",
                        source, self.name, k, warn_key[2], self.statistic,
                    )
        if not merged:
            logger.error(
                "No %s reference (neither %s nor the bundled %s)",
                self.name, self.live_path, self.bundled_path,
            )
        if unreadable:
            # Kept, the other file's entries would stand until one changed.
            raise Uncached(merged)
        return merged

    def write(self, chamber: str, reference: dict) -> None:
        """Persist this run's reference for one chamber (read-merge-write,
        under the file's lock: each chamber's pipeline owns its own key, and
        the two can write at once). Never raises — the
        pipeline has already scored with the in-memory reference; this file
        is for readers outside the run."""
        try:
            entry = {**reference, "computed_at": utcnow().isoformat(timespec="seconds")}
            update_json_file(
                self.live_path, lambda existing: {**existing, chamber: entry}, indent=2, sort_keys=True, end="\n",
            )
            self._cache = None
        except Exception:
            logger.warning(
                "Failed to write %s for %s — API score breakdowns may show the "
                "previous run's reference until the next write.",
                self.live_path, chamber, exc_info=True,
            )

    def with_live(self, chamber: str, reference: dict | None) -> dict:
        """The full per-chamber reference for scoring this run: this run's
        value for `chamber` (persisted) over the last persisted one for the
        other chamber. None keeps the last persisted value for `chamber`."""
        if reference is None:
            return self.load()
        self.write(chamber, reference)
        return {**self.load(), chamber: reference}


LES_REFERENCE = ChamberReference("les_reference")
FUNDING_REFERENCE = ChamberReference("funding_reference")
CONSTITUENT_REFERENCE = ChamberReference("constituent_reference", statistic=CONSTITUENT_REFERENCE_STATISTIC)
PRESIDENT_REFERENCE = ChamberReference("president_reference", keys=("presidents",))
