"""Per-chamber population references the pipeline measures every run.

Several scoring components compare a member against their chamber's own
population — the median member's bill credit (Legislative Effectiveness),
the median member's PAC share (Funding Independence). Those reference
values used to be Python literals pasted from a calibration script's
output (AGENTS.md §3a), which drift as the population changes. Instead the
pipeline measures each one from the members it is about to score, passes it
to calculate_scores, and persists it here so readers outside the run (the
API's on-demand score breakdowns, scripts/rescore.py) reproduce the
pipeline's numbers.

Each reference has two files:
  - /data/<name>.json — the last run's values, per chamber (the app's
    writable volume; app/data/ is baked into the image read-only — see
    score_calculator._party_ideology_bounds for the production crash that
    rule comes from);
  - app/data/<name>.json — a bundled fallback for before a deployment's
    first run, regenerated by the script its `_source` names.
"""

import json
import logging
import pathlib

from app.time_utils import utcnow

logger = logging.getLogger(__name__)

_BUNDLED_DIR = pathlib.Path(__file__).resolve().parent.parent.parent / "data"
_LIVE_DIR = pathlib.Path("/data")
CHAMBERS = ("senate", "house")


def _read_json(path: pathlib.Path) -> dict:
    try:
        return json.loads(path.read_text())
    except Exception:
        return {}


def _mtime(path: pathlib.Path) -> float | None:
    try:
        return path.stat().st_mtime
    except OSError:
        return None


class ChamberReference:
    """One named reference: {"senate": {...}, "house": {...}}."""

    def __init__(self, name: str):
        self.name = name
        self.live_path = _LIVE_DIR / f"{name}.json"
        self.bundled_path = _BUNDLED_DIR / f"{name}.json"
        self._cache: tuple[tuple[float | None, float | None], dict] | None = None

    def load(self) -> dict:
        """The live file layered over the bundled fallback, per chamber.
        Re-read whenever either file changes on disk (mtime), so the API
        worker that didn't run the pipeline doesn't keep serving the
        previous run's numbers."""
        key = (_mtime(self.live_path), _mtime(self.bundled_path))
        if self._cache is not None and self._cache[0] == key:
            return self._cache[1]
        bundled, live = _read_json(self.bundled_path), _read_json(self.live_path)
        merged = {ch: live.get(ch) or bundled.get(ch) for ch in CHAMBERS if live.get(ch) or bundled.get(ch)}
        if not merged:
            logger.error(
                "No %s reference (neither %s nor the bundled %s)",
                self.name, self.live_path, self.bundled_path,
            )
        self._cache = (key, merged)
        return merged

    def write(self, chamber: str, reference: dict) -> None:
        """Persist this run's reference for one chamber (read-merge-write:
        each chamber's pipeline owns its own key). Never raises — the
        pipeline has already scored with the in-memory reference; this file
        is for readers outside the run."""
        try:
            existing = _read_json(self.live_path)
            existing[chamber] = {**reference, "computed_at": utcnow().isoformat(timespec="seconds")}
            self.live_path.write_text(json.dumps(existing, indent=2, sort_keys=True) + "\n")
            self._cache = None
        except Exception:
            logger.warning(
                "Failed to write %s for %s — API score breakdowns may show the "
                "previous run's reference until the next write.",
                self.live_path, chamber, exc_info=True,
            )

    def with_live(self, chamber: str, reference: dict | None) -> dict:
        """The full per-chamber reference for scoring this run: this run's
        value for `chamber` (persisted) over the last persisted one for the
        other chamber. None keeps the last persisted value for `chamber`."""
        if reference is None:
            return self.load()
        self.write(chamber, reference)
        return {**self.load(), chamber: reference}


LES_REFERENCE = ChamberReference("les_reference")
FUNDING_REFERENCE = ChamberReference("funding_reference")
