"""Fetch the frontend's web fonts from Google Fonts into the repo.

Writes frontend/src/app/fonts/*.woff2 and fonts/manifest.json, which
frontend/src/app/fonts.ts loads through next/font/local. The site used to
load them with next/font/google, which downloads them during `next build`;
about one build in five failed there, because Google intermittently answers
with a `fonts.gstatic.com/l/font?kit=...` URL that Turbopack's loader
rejects. Committing the files takes the network out of the build.

What this fetches is exactly what next/font/google fetched: the same CSS2
request, with next's own User-Agent (Google picks the file format from it),
one woff2 per script subset, each behind Google's unicode-range. The
manifest records those ranges and the preload rule, and
frontend/src/app/fonts.test.ts fails if fonts.ts drifts from it.

The files are committed byte-for-byte as Google serves them. The
metric-matched fallbacks (local Arial resized to each face's proportions,
which text renders in until the font arrives) are written here too, to
fonts/fallback.css, rather than generated by next/font/local: that measures
a variable font at its default instance, and Archivo's default is wght 600,
so its fallback came out sized for SemiBold — about 4% too wide for the
400-weight prose it stands in for, which then reflowed when the font
loaded. Instead this uses the source next/font/google used: capsize's
per-family metrics, which Next ships as capsize-font-metrics.json, run
through Next's own formula (next/dist/server/font-utils.js). The three
fallbacks come out identical to the ones the site had before.

Rerun when a face should move to a newer Google release:

    (cd ../frontend && npm ci)   # for Next's capsize metrics
    python scripts/fetch_site_fonts.py
"""

from __future__ import annotations

import json
import re
import sys
import time
from datetime import UTC, datetime
from pathlib import Path

import httpx

FRONTEND = Path(__file__).resolve().parents[2] / "frontend"
FONTS_DIR = FRONTEND / "src" / "app" / "fonts"
CAPSIZE_METRICS = (
    FRONTEND / "node_modules" / "next" / "dist" / "server" / "capsize-font-metrics.json"
)

# next/font/google's own User-Agent (next/dist/compiled/@next/font/dist/
# google/fetch-resource.js), so Google answers with the same woff2 files.
USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36"
)

# The same families and axes the root layout asked next/font/google for,
# and each one's key in capsize's metrics (next's formatName: camelCase).
FAMILIES = {
    "archivo": ("Archivo:wght@400;600;800", "archivo"),
    "press-start-2p": ("Press+Start+2P", "pressStart2P"),
    "share-tech-mono": ("Share+Tech+Mono", "shareTechMono"),
}

# next/font/google was called with subsets: ["latin"] — only these preload.
PRELOADED_SUBSET = "latin"

# Only files served from /s/<family>/ are Google's own per-subset files; the
# /l/font?kit= form is the answer that broke the build, so ask again.
_STATIC_SRC = re.compile(r"https://fonts\.gstatic\.com/s/[^)]+\.woff2")
_BLOCK = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*{([^}]*)}")
_ATTEMPTS = 5


def _css(client: httpx.Client, query: str) -> str:
    url = f"https://fonts.googleapis.com/css2?family={query}&display=swap"
    for attempt in range(_ATTEMPTS):
        css = client.get(url).raise_for_status().text
        if "/l/font?" not in css:
            return css
        if attempt < _ATTEMPTS - 1:
            time.sleep(2**attempt)
    sys.exit(f"Google kept answering {url} with /l/font URLs")


def _faces(css: str) -> dict[str, dict]:
    """subset -> {src, unicodeRange, weights} from one CSS2 response."""
    faces: dict[str, dict] = {}
    for subset, body in _BLOCK.findall(css):
        src = _STATIC_SRC.search(body)
        weight = re.search(r"font-weight:\s*(\d+)", body)
        ranges = re.search(r"unicode-range:\s*([^;]+);", body)
        if not (src and weight and ranges):
            sys.exit(f"unexpected @font-face for {subset}: {body.strip()}")
        face = faces.setdefault(
            subset,
            {
                "src": src.group(0),
                "unicodeRange": ranges.group(1).strip(),
                "weights": [],
            },
        )
        if face["src"] != src.group(0):
            sys.exit(
                f"{subset}: one file per subset expected, got {face['src']} and {src.group(0)}"
            )
        face["weights"].append(weight.group(1))
    return faces


def _fallback_css(family: str, key: str, capsize: dict) -> str:
    """An @font-face resizing local Arial to one face's capsize metrics, by
    next/font/google's formula (calculateSizeAdjustValues). Arial is its
    fallback for every category but serif, which none of these faces is."""
    font, arial = capsize[key], capsize["arial"]
    if font["category"] == "serif":
        sys.exit(f"{key} is a serif face; its fallback would be Times New Roman")
    upem = font["unitsPerEm"]
    size_adjust = (font["xWidthAvg"] / upem) / (
        arial["xWidthAvg"] / arial["unitsPerEm"]
    )

    def pct(value: float) -> str:
        # Trailing zeros dropped, as prettier (format:check) writes numbers.
        return f"{abs(value * 100):.2f}".rstrip("0").rstrip(".") + "%"

    return (
        f'@font-face {{\n  font-family: "{family}";\n  src: local("Arial");\n'
        f"  ascent-override: {pct(font['ascent'] / (upem * size_adjust))};\n"
        f"  descent-override: {pct(font['descent'] / (upem * size_adjust))};\n"
        f"  line-gap-override: {pct(font['lineGap'] / (upem * size_adjust))};\n"
        f"  size-adjust: {pct(size_adjust)};\n}}\n"
    )


def main() -> None:
    if not CAPSIZE_METRICS.exists():
        sys.exit(f"{CAPSIZE_METRICS} not found; run `npm ci` in frontend/ first")
    capsize = json.loads(CAPSIZE_METRICS.read_text())
    manifest_path = FONTS_DIR / "manifest.json"
    fonts: dict[str, dict] = {}
    fallbacks = []
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    with httpx.Client(headers={"User-Agent": USER_AGENT}, timeout=30) as client:
        for name, (query, capsize_key) in FAMILIES.items():
            family = capsize[capsize_key]["familyName"]
            entries = []
            for subset, face in _faces(_css(client, query)).items():
                data = client.get(face["src"]).raise_for_status().content
                file = f"{name}-{subset}.woff2"
                (FONTS_DIR / file).write_bytes(data)
                entries.append(
                    {
                        "subset": subset,
                        "file": file,
                        "weights": face["weights"],
                        "unicodeRange": face["unicodeRange"],
                        "preload": subset == PRELOADED_SUBSET,
                    }
                )
                print(f"{file}: {len(data)} bytes, weights {face['weights']}")
            fonts[name] = {"fallback": f"{family} Fallback", "files": entries}
            fallbacks.append(_fallback_css(f"{family} Fallback", capsize_key, capsize))

    # Keep the old date when nothing changed, so a rerun that finds the same
    # files leaves the manifest untouched.
    previous = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}
    source = previous.get("_source") if previous.get("fonts") == fonts else None
    manifest = {
        "_source": source
        or (
            "Google Fonts CSS2 API with next/font/google's User-Agent; fallbacks from "
            "Next's capsize-font-metrics.json. Fetched by backend/scripts/fetch_site_fonts.py "
            f"on {datetime.now(UTC).date().isoformat()}"
        ),
        "fonts": fonts,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    (FONTS_DIR / "fallback.css").write_text(
        "/* Generated by backend/scripts/fetch_site_fonts.py - do not edit.\n"
        "   Each face's metric-matched Arial fallback (see the script). */\n"
        + "\n".join(fallbacks)
    )


if __name__ == "__main__":
    main()
