"""When a state's last polls close on a general election day, read from
app/data/poll_close_times.json (generated by
scripts/fetch_poll_close_times.py from each state's statute as Ballotpedia
tabulates it — regenerate each cycle).

The live-results sync stores nothing for a state until this moment: no
count, no "flip", no post. Florida and Nevada criminalize releasing
results before polls close, a state spanning two time zones is still
voting in its western part after the eastern part closes, and a count on
the page before a reader's polls close is the thing election-night
reporting is most careful never to do.
"""

import json
from datetime import date, datetime, time, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

_PATH = Path(__file__).resolve().parents[2] / "data" / "poll_close_times.json"
_cache: dict | None = None


def _states() -> dict:
    global _cache
    if _cache is None:
        _cache = (json.loads(_PATH.read_text()).get("states") or {}) if _PATH.exists() else {}
    return _cache


def _close_utc(entry: dict, election_day: date) -> datetime | None:
    if not entry.get("close"):
        return None
    hour, minute = (int(x) for x in entry["close"].split(":"))
    local = datetime.combine(election_day, time(hour, minute), ZoneInfo(entry["zone"]))
    return local.astimezone(timezone.utc).replace(tzinfo=None)


def last_poll_close(state: str, election_day: date) -> datetime:
    """Naive UTC instant of `state`'s last poll closing. A state whose
    hours vary, or that the file doesn't list, waits for the latest close
    of any listed state — the gate errs toward waiting."""
    states = _states()
    own = _close_utc(states.get(state.upper()) or {}, election_day)
    if own is not None:
        return own
    closes = [c for e in states.values() if (c := _close_utc(e, election_day)) is not None]
    if closes:
        return max(closes)
    # No file at all: nothing before the end of election day in Hawaii.
    return datetime.combine(election_day, time(23, 59), ZoneInfo("Pacific/Honolulu")).astimezone(
        timezone.utc,
    ).replace(tzinfo=None)


def polls_closed(state: str, election_day: date, now: datetime) -> bool:
    """`now` is naive UTC (time_utils.utcnow)."""
    return now >= last_poll_close(state, election_day)
