"""How a member's own constituents rated them in the Cooperative Election
Study, split by the respondent's party: app/data/ces_member_approval.json,
generated by scripts/fetch_ces_approval.py (which documents the estimates
and the shrinkage). Informational; no score reads it.

The survey names the member each respondent was asked about (the incumbent
when it was fielded), by seat. A member record is joined to it by chamber,
state and name, so a member who took office after the survey, or who has
changed chambers since, has no reading rather than their predecessor's.
"""

import json
import logging
import pathlib
import re
import unicodedata

from app.time_utils import utcnow

logger = logging.getLogger(__name__)

_DATA = pathlib.Path(__file__).resolve().parent.parent / "data" / "ces_member_approval.json"
_survey_cache: dict | None = None

# Respondent parties in display order.
PARTIES = ("D", "R", "I")
# Generational suffixes are not part of the surname ("Bob Casey Jr.").
_SUFFIXES = frozenset({"jr", "sr", "ii", "iii", "iv"})


def _survey() -> dict:
    global _survey_cache
    if _survey_cache is None:
        try:
            _survey_cache = json.loads(_DATA.read_text())
        except Exception:
            logger.warning("Constituent survey data unavailable (%s)", _DATA, exc_info=True)
            _survey_cache = {}
    return _survey_cache


def _name_parts(name: str) -> tuple[str, str] | None:
    """(first initial, surname), accents and punctuation ignored."""
    plain = unicodedata.normalize("NFD", name or "").encode("ascii", "ignore").decode()
    words = [w for w in re.sub(r"[^a-z ]+", " ", plain.lower().replace("'", "")).split() if w not in _SUFFIXES]
    words = [w for w in words if len(w) > 1] or words
    if len(words) < 2:
        return None
    return words[0][0], words[-1]


def _initials(name: str) -> set[str]:
    """The first initial, and a quoted nickname's ("Earl L. \"Buddy\"
    Carter" is also Buddy Carter)."""
    parts = _name_parts(name)
    nicknames = [n.strip().lower()[:1] for n in re.findall(r'"([^"]+)"', name or "") if n.strip()]
    return ({parts[0]} if parts else set()) | set(nicknames)


def _entry_for(chamber: str, state: str, name: str, district: int | None, party: str | None) -> dict | None:
    """The survey's entry for this member, by chamber, state and surname,
    among members of the same party (and for the House, the same district
    when the surname alone is ambiguous). A first initial that matches,
    directly or through a quoted nickname, settles it; failing that, a
    unique same-surname, same-party entry for the seat stands for a first
    name the survey spells differently ("Bob Doe" for "Robert J.
    Doe"). constituent_approval only asks for members already in office
    when the survey was fielded, which is what keeps a namesake successor
    (a relative who succeeds a member) from inheriting the reading."""
    parts = _name_parts(name)
    if parts is None:
        return None
    candidates = [
        m for m in _survey().get("members", [])
        if m["chamber"] == chamber and m["state"] == state
        and (_name_parts(m["name"]) or ("", ""))[1] == parts[1]
        and (party is None or m.get("member_party") in (party, "I") or party == "I")
    ]
    if chamber == "house":
        # Only the district the member represents now: a member redistricted
        # into another seat (as one was in 2026) was rated by other
        # people. An at-large seat is district 0 here and "1" in the survey.
        seat = "1" if district == 0 else str(district)
        candidates = [m for m in candidates if m.get("district") == seat]
    initials = _initials(name)
    by_initial = [m for m in candidates if (_name_parts(m["name"]) or ("",))[0] in initials]
    if len(by_initial) == 1:
        return by_initial[0]
    return candidates[0] if len(candidates) == 1 and not by_initial else None


def constituent_approval(
    chamber: str, state: str, name: str, party: str | None,
    years_in_office: int, district: int | None = None,
) -> dict | None:
    """The member's reading, shaped for ConstituentApprovalSchema, or None
    when the survey has none for them. Only a member already in this
    chamber when the survey was fielded can have one: years_in_office
    counts from the first term's start year (normalize_members), so it is
    at least (this year - the survey's year) for them."""
    fielded_year = _survey().get("fielded_year")
    if not fielded_year or years_in_office < utcnow().year - fielded_year:
        return None
    entry = _entry_for(chamber, state, name, district, party)
    if entry is None:
        return None
    by_party = []
    for party in PARTIES:
        est = entry["by_party"].get(party)
        if not est:
            continue
        by_party.append({
            "party": party,
            # None: the survey can't tell members apart in this cell (see
            # fetch_ces_approval.priors), so no per-member figure is shown.
            "approve": est.get("shrunk"),
            # Share of the figure that is this member's own respondents; the
            # rest is the typical member's (the shrinkage).
            "own_weight": est.get("own_weight"),
            "respondents": est["n"],
        })
    data = _survey()
    return {
        "survey": data.get("survey", ""),
        "fielded": data.get("fielded", ""),
        "surveyed_as": entry["name"],
        "by_party": by_party,
    }
