"""Baseline: the main database's schema as of ALGORITHM_VERSION v6.13.

Autogenerated from the models (app.models) against an empty database,
then made idempotent per table. It is a frozen snapshot: when a model
changes, write a NEW revision; never edit this one.

Revision ID: 0001
Revises:
Create Date: 2026-09-24
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Each table (and its indexes) is created only if absent, so this
    # revision can also be applied to a database that predates Alembic:
    # init_db first brings such a database's existing tables to this
    # shape with the frozen pre-Alembic bridge, then upgrades, and the
    # baseline only fills in tables it lacks.
    existing = set(sa.inspect(op.get_bind()).get_table_names())

    if 'action_issues' not in existing:
        op.create_table('action_issues',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date', sa.String(length=10), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('facts', sa.Text(), nullable=False),
        sa.Column('actions', sa.Text(), nullable=False),
        sa.Column('source_urls', sa.Text(), nullable=False),
        sa.Column('source_names', sa.Text(), nullable=False),
        sa.Column('policy_areas', sa.Text(), nullable=False),
        sa.Column('related_bill_ids', sa.Text(), nullable=False),
        sa.Column('related_explore_ids', sa.Text(), nullable=False),
        sa.Column('related_senators', sa.Text(), nullable=False),
        sa.Column('related_officials', sa.Text(), nullable=True),
        sa.Column('fact_sources', sa.Text(), nullable=False),
        sa.Column('related_monitor_slugs', sa.Text(), nullable=False),
        sa.Column('concerned_count', sa.Integer(), nullable=False),
        sa.Column('not_priority_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('full_story', sa.Text(), nullable=True),
        sa.Column('bsky_posted_at', sa.DateTime(), nullable=True),
        sa.Column('bsky_posted_rank', sa.Integer(), nullable=True),
        sa.Column('bsky_last_post_text', sa.Text(), nullable=True),
        sa.Column('bsky_posted_facts', sa.Text(), nullable=True),
        sa.Column('previous_facts', sa.Text(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('primary_article_date', sa.String(length=10), nullable=True),
        sa.Column('image_url', sa.Text(), nullable=True),
        sa.Column('image_alt', sa.Text(), nullable=False),
        sa.Column('image_credit', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('source_type', sa.String(length=40), nullable=True),
        sa.Column('primary_source_url', sa.Text(), nullable=True),
        sa.Column('confirmation_deadline', sa.DateTime(), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('action_issues', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_action_issues_date'), ['date'], unique=False)

    if 'analysis_cache' not in existing:
        op.create_table('analysis_cache',
        sa.Column('prompt_version', sa.String(), nullable=False),
        sa.Column('input_hash', sa.String(), nullable=False),
        sa.Column('result_json', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('prompt_version', 'input_hash')
        )

    if 'api_cache' not in existing:
        op.create_table('api_cache',
        sa.Column('tier', sa.String(), nullable=False),
        sa.Column('cache_key', sa.String(), nullable=False),
        sa.Column('data_json', sa.Text(), nullable=False),
        sa.Column('cached_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('tier', 'cache_key')
        )

    if 'ballot_measures' not in existing:
        op.create_table('ballot_measures',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('election_date', sa.String(length=10), nullable=False),
        sa.Column('election_type', sa.String(length=16), nullable=False),
        sa.Column('number', sa.String(length=64), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('measure_type', sa.String(length=64), nullable=True),
        sa.Column('origin', sa.String(length=64), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('official_title', sa.Text(), nullable=True),
        sa.Column('official_summary', sa.Text(), nullable=True),
        sa.Column('fiscal_impact', sa.Text(), nullable=True),
        sa.Column('yes_means', sa.Text(), nullable=True),
        sa.Column('no_means', sa.Text(), nullable=True),
        sa.Column('title_authority', sa.String(length=200), nullable=True),
        sa.Column('fiscal_authority', sa.String(length=200), nullable=True),
        sa.Column('source_name', sa.String(length=200), nullable=False),
        sa.Column('source_url', sa.String(), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(), nullable=False),
        sa.Column('as_of', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('ballot_measures', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_ballot_measures_election_date'), ['election_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_ballot_measures_state'), ['state'], unique=False)
            batch_op.create_index('uq_ballot_measure_state_date_number', ['state', 'election_date', 'number'], unique=True, sqlite_where=sa.text("number != ''"))

    if 'bsky_senator_spotlights' not in existing:
        op.create_table('bsky_senator_spotlights',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('senator_id', sa.String(length=32), nullable=False),
        sa.Column('chamber', sa.String(length=10), nullable=False),
        sa.Column('posted_at', sa.DateTime(), nullable=False),
        sa.Column('post_text', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('bsky_senator_spotlights', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_bsky_senator_spotlights_senator_id'), ['senator_id'], unique=False)

    if 'election_pipeline_runs' not in existing:
        op.create_table('election_pipeline_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('current_phase', sa.String(), nullable=True),
        sa.Column('candidates_synced', sa.Integer(), nullable=False),
        sa.Column('financials_refreshed', sa.Integer(), nullable=False),
        sa.Column('coverage_items_ingested', sa.Integer(), nullable=False),
        sa.Column('elapsed_seconds', sa.Float(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('progress_detail', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'explore_documents' not in existing:
        op.create_table('explore_documents',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('doc_type', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('politician_name', sa.String(), nullable=True),
        sa.Column('politician_id', sa.String(), nullable=True),
        sa.Column('chamber', sa.String(), nullable=True),
        sa.Column('agency_name', sa.String(), nullable=True),
        sa.Column('comment_url', sa.String(), nullable=True),
        sa.Column('comments_close_on', sa.String(), nullable=True),
        sa.Column('policy_areas', sa.Text(), nullable=False),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('body_fetched_at', sa.DateTime(), nullable=True),
        sa.Column('identifiers', sa.Text(), nullable=False),
        sa.Column('authority', sa.Float(), nullable=False),
        sa.Column('cited_by_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('external_id')
        )
        with op.batch_alter_table('explore_documents', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_explore_documents_date'), ['date'], unique=False)
            batch_op.create_index(batch_op.f('ix_explore_documents_doc_type'), ['doc_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_explore_documents_politician_id'), ['politician_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_explore_documents_politician_name'), ['politician_name'], unique=False)

    if 'house_pipeline_runs' not in existing:
        op.create_table('house_pipeline_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('reps_processed', sa.Integer(), nullable=False),
        sa.Column('reps_total', sa.Integer(), nullable=False),
        sa.Column('reps_failed', sa.Integer(), nullable=False),
        sa.Column('elapsed_seconds', sa.Float(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('ground_truth_failures', sa.Text(), nullable=True),
        sa.Column('progress_detail', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'judicial_nominees' not in existing:
        op.create_table('judicial_nominees',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('cycle_year', sa.Integer(), nullable=False),
        sa.Column('court', sa.String(length=10), nullable=False),
        sa.Column('district', sa.String(length=8), nullable=True),
        sa.Column('seat', sa.String(length=8), nullable=True),
        sa.Column('party', sa.String(length=1), nullable=False),
        sa.Column('display_name', sa.String(length=200), nullable=False),
        sa.Column('source_name', sa.String(length=200), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('state', 'cycle_year', 'court', 'district', 'seat', 'party', 'display_name', name='uq_judicial_nominee_seat_party_name')
        )
        with op.batch_alter_table('judicial_nominees', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_judicial_nominees_cycle_year'), ['cycle_year'], unique=False)
            batch_op.create_index(batch_op.f('ix_judicial_nominees_state'), ['state'], unique=False)

    if 'justices' not in existing:
        op.create_table('justices',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('role_title', sa.String(), nullable=False),
        sa.Column('appointing_president', sa.String(), nullable=True),
        sa.Column('appointing_party', sa.String(), nullable=True),
        sa.Column('date_start', sa.String(), nullable=True),
        sa.Column('date_end', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('thumbnail_url', sa.String(), nullable=True),
        sa.Column('score_consistency', sa.Float(), nullable=False),
        sa.Column('score_independence', sa.Float(), nullable=False),
        sa.Column('cases_decided', sa.Integer(), nullable=False),
        sa.Column('majority_pct', sa.Float(), nullable=False),
        sa.Column('dissent_pct', sa.Float(), nullable=False),
        sa.Column('unanimous_pct', sa.Float(), nullable=False),
        sa.Column('authored_majority', sa.Integer(), nullable=False),
        sa.Column('authored_dissent', sa.Integer(), nullable=False),
        sa.Column('authored_concurrence', sa.Integer(), nullable=False),
        sa.Column('close_case_majority_pct', sa.Float(), nullable=False),
        sa.Column('cross_bloc_pct', sa.Float(), nullable=False),
        sa.Column('agreement_matrix', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    if 'learned_classifications' not in existing:
        op.create_table('learned_classifications',
        sa.Column('entity_name', sa.String(), nullable=False),
        sa.Column('entity_type', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('model_version', sa.String(), nullable=True),
        sa.Column('match_metadata', sa.Text(), nullable=True),
        sa.Column('learned_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('entity_name', 'entity_type')
        )

    if 'llm_generation_samples' not in existing:
        op.create_table('llm_generation_samples',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('task', sa.String(length=50), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('attempt', sa.Integer(), nullable=False),
        sa.Column('input_text', sa.Text(), nullable=False),
        sa.Column('output_json', sa.Text(), nullable=False),
        sa.Column('passed', sa.Boolean(), nullable=False),
        sa.Column('violations', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('llm_generation_samples', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_llm_generation_samples_task'), ['task'], unique=False)

    if 'measure_coverage' not in existing:
        op.create_table('measure_coverage',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('election_date', sa.String(length=10), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('source_name', sa.String(length=200), nullable=True),
        sa.Column('measure_count', sa.Integer(), nullable=False),
        sa.Column('checked_at', sa.DateTime(), nullable=False),
        sa.Column('error_detail', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('state', 'election_date', name='uq_measure_coverage_state_date')
        )
        with op.batch_alter_table('measure_coverage', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_measure_coverage_election_date'), ['election_date'], unique=False)
            batch_op.create_index(batch_op.f('ix_measure_coverage_state'), ['state'], unique=False)

    if 'month_summaries' not in existing:
        op.create_table('month_summaries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('month', sa.Integer(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('top_policy_areas', sa.Text(), nullable=False),
        sa.Column('entry_count', sa.Integer(), nullable=False),
        sa.Column('generated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('month_summaries', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_month_summaries_year'), ['year'], unique=False)

    if 'national_monitors' not in existing:
        op.create_table('national_monitors',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('slug', sa.String(length=200), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('policy_areas', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_article_date', sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('national_monitors', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_national_monitors_slug'), ['slug'], unique=True)
            batch_op.create_index(batch_op.f('ix_national_monitors_status'), ['status'], unique=False)

    if 'pipeline_phase_timings' not in existing:
        op.create_table('pipeline_phase_timings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_kind', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.Integer(), nullable=False),
        sa.Column('step_key', sa.String(length=64), nullable=False),
        sa.Column('phase', sa.String(length=32), nullable=False),
        sa.Column('label', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('duration_seconds', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('run_kind', 'run_id', 'step_key', name='uq_phase_timing_run_step')
        )
        with op.batch_alter_table('pipeline_phase_timings', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_pipeline_phase_timings_run_id'), ['run_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_pipeline_phase_timings_run_kind'), ['run_kind'], unique=False)

    if 'pipeline_rate_limit_stats' not in existing:
        op.create_table('pipeline_rate_limit_stats',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('run_kind', sa.String(length=64), nullable=False),
        sa.Column('run_id', sa.Integer(), nullable=False),
        sa.Column('step_key', sa.String(length=64), nullable=False),
        sa.Column('source', sa.String(length=64), nullable=False),
        sa.Column('requests', sa.Integer(), nullable=False),
        sa.Column('blocked_seconds', sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('run_kind', 'run_id', 'step_key', 'source', name='uq_rate_limit_stat_run_step_source')
        )
        with op.batch_alter_table('pipeline_rate_limit_stats', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_pipeline_rate_limit_stats_run_id'), ['run_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_pipeline_rate_limit_stats_run_kind'), ['run_kind'], unique=False)

    if 'pipeline_runs' not in existing:
        op.create_table('pipeline_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('current_phase', sa.String(), nullable=True),
        sa.Column('senators_processed', sa.Integer(), nullable=False),
        sa.Column('senators_total', sa.Integer(), nullable=False),
        sa.Column('senators_failed', sa.Integer(), nullable=False),
        sa.Column('bills_classified', sa.Integer(), nullable=False),
        sa.Column('llm_calls', sa.Integer(), nullable=False),
        sa.Column('cache_hits', sa.Integer(), nullable=False),
        sa.Column('cache_misses', sa.Integer(), nullable=False),
        sa.Column('elapsed_seconds', sa.Float(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('progress_detail', sa.Text(), nullable=True),
        sa.Column('ground_truth_failures', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'presidents' not in existing:
        op.create_table('presidents',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('party', sa.String(), nullable=False),
        sa.Column('number', sa.Integer(), nullable=False),
        sa.Column('term_start', sa.String(), nullable=False),
        sa.Column('term_end', sa.String(), nullable=True),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('score_public_mandate', sa.Float(), nullable=True),
        sa.Column('score_effectiveness', sa.Float(), nullable=True),
        sa.Column('score_agency_alignment', sa.Float(), nullable=True),
        sa.Column('score_historical_legacy', sa.Float(), nullable=True),
        sa.Column('avg_approval', sa.Float(), nullable=True),
        sa.Column('election_margin', sa.Float(), nullable=True),
        sa.Column('gdp_growth_avg', sa.Float(), nullable=True),
        sa.Column('jobs_created_millions', sa.Float(), nullable=True),
        sa.Column('eo_count', sa.Integer(), nullable=True),
        sa.Column('rulemaking_count', sa.Integer(), nullable=True),
        sa.Column('rulemaking_finalized_pct', sa.Float(), nullable=True),
        sa.Column('approval_trend', sa.Float(), nullable=True),
        sa.Column('historical_legacy_score', sa.Integer(), nullable=True),
        sa.Column('recent_avg_approval', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )

    if 'races' not in existing:
        op.create_table('races',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('cycle_year', sa.Integer(), nullable=False),
        sa.Column('office', sa.String(length=1), nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('district', sa.Integer(), nullable=True),
        sa.Column('is_special', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('races', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_races_cycle_year'), ['cycle_year'], unique=False)
            batch_op.create_index(batch_op.f('ix_races_state'), ['state'], unique=False)

    if 'representatives' not in existing:
        op.create_table('representatives',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('bioguide_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('district', sa.Integer(), nullable=False),
        sa.Column('party', sa.String(length=1), nullable=False),
        sa.Column('years_in_office', sa.Integer(), nullable=False),
        sa.Column('initials', sa.String(length=4), nullable=False),
        sa.Column('leadership_title', sa.String(), nullable=True),
        sa.Column('committees', sa.Text(), nullable=False),
        sa.Column('score_funding_independence', sa.Float(), nullable=False),
        sa.Column('score_promise_persistence', sa.Float(), nullable=False),
        sa.Column('score_independent_voting', sa.Float(), nullable=False),
        sa.Column('score_funding_diversity', sa.Float(), nullable=False),
        sa.Column('score_legislative_effectiveness', sa.Float(), nullable=False),
        sa.Column('score_confidence', sa.Text(), nullable=False),
        sa.Column('total_raised', sa.Float(), nullable=False),
        sa.Column('total_contributions', sa.Float(), nullable=True),
        sa.Column('caucus_party', sa.String(length=1), nullable=True),
        sa.Column('total_from_pacs', sa.Float(), nullable=False),
        sa.Column('small_donor_percentage', sa.Float(), nullable=False),
        sa.Column('partisan_depth', sa.Text(), nullable=True),
        sa.Column('leadership_score', sa.Float(), nullable=True),
        sa.Column('ideology_score', sa.Float(), nullable=True),
        sa.Column('bipartisanship_score', sa.Float(), nullable=True),
        sa.Column('attracted_bipartisanship_score', sa.Float(), nullable=True),
        sa.Column('sponsorship_description', sa.String(), nullable=False),
        sa.Column('website_url', sa.String(), nullable=False),
        sa.Column('contact_form_url', sa.String(), nullable=False),
        sa.Column('office_phone', sa.String(length=20), nullable=False),
        sa.Column('office_address', sa.String(), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('vacancy_reason', sa.String(), nullable=True),
        sa.Column('left_office_date', sa.String(length=10), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('representatives', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_representatives_state'), ['state'], unique=False)

    if 'score_snapshots' not in existing:
        op.create_table('score_snapshots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('entity_type', sa.String(length=20), nullable=False),
        sa.Column('entity_id', sa.String(), nullable=False),
        sa.Column('date', sa.String(length=10), nullable=False),
        sa.Column('overall_score', sa.Float(), nullable=False),
        sa.Column('score_1', sa.Float(), nullable=False),
        sa.Column('score_2', sa.Float(), nullable=False),
        sa.Column('score_3', sa.Float(), nullable=False),
        sa.Column('score_4', sa.Float(), nullable=False),
        sa.Column('score_5', sa.Float(), nullable=False),
        sa.Column('algorithm_version', sa.String(length=16), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_score_snapshots_date'), ['date'], unique=False)
            batch_op.create_index(batch_op.f('ix_score_snapshots_entity_id'), ['entity_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_score_snapshots_entity_type'), ['entity_type'], unique=False)

    if 'senators' not in existing:
        op.create_table('senators',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('bioguide_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('party', sa.String(length=1), nullable=False),
        sa.Column('years_in_office', sa.Integer(), nullable=False),
        sa.Column('initials', sa.String(length=4), nullable=False),
        sa.Column('is_current', sa.Boolean(), nullable=False),
        sa.Column('vacancy_reason', sa.String(), nullable=True),
        sa.Column('left_office_date', sa.String(length=10), nullable=True),
        sa.Column('leadership_title', sa.String(), nullable=True),
        sa.Column('committees', sa.Text(), nullable=False),
        sa.Column('score_funding_independence', sa.Float(), nullable=False),
        sa.Column('score_promise_persistence', sa.Float(), nullable=False),
        sa.Column('score_independent_voting', sa.Float(), nullable=False),
        sa.Column('score_funding_diversity', sa.Float(), nullable=False),
        sa.Column('score_legislative_effectiveness', sa.Float(), nullable=False),
        sa.Column('score_confidence', sa.Text(), nullable=False),
        sa.Column('total_raised', sa.Float(), nullable=False),
        sa.Column('total_contributions', sa.Float(), nullable=True),
        sa.Column('caucus_party', sa.String(length=1), nullable=True),
        sa.Column('total_from_pacs', sa.Float(), nullable=False),
        sa.Column('small_donor_percentage', sa.Float(), nullable=False),
        sa.Column('partisan_depth', sa.Text(), nullable=True),
        sa.Column('leadership_score', sa.Float(), nullable=True),
        sa.Column('ideology_score', sa.Float(), nullable=True),
        sa.Column('bipartisanship_score', sa.Float(), nullable=True),
        sa.Column('attracted_bipartisanship_score', sa.Float(), nullable=True),
        sa.Column('sponsorship_description', sa.String(), nullable=False),
        sa.Column('website_url', sa.String(), nullable=False),
        sa.Column('contact_form_url', sa.String(), nullable=False),
        sa.Column('office_phone', sa.String(length=20), nullable=False),
        sa.Column('office_address', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('senators', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_senators_state'), ['state'], unique=False)

    if 'state_leg_nominees' not in existing:
        op.create_table('state_leg_nominees',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('cycle_year', sa.Integer(), nullable=False),
        sa.Column('chamber', sa.String(length=8), nullable=False),
        sa.Column('district', sa.String(length=8), nullable=False),
        sa.Column('seat', sa.String(length=4), nullable=True),
        sa.Column('party', sa.String(length=1), nullable=False),
        sa.Column('display_name', sa.String(length=200), nullable=False),
        sa.Column('source_name', sa.String(length=200), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('state', 'cycle_year', 'chamber', 'district', 'seat', 'party', 'display_name', name='uq_state_leg_nominee_seat_party_name')
        )
        with op.batch_alter_table('state_leg_nominees', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_state_leg_nominees_cycle_year'), ['cycle_year'], unique=False)
            batch_op.create_index(batch_op.f('ix_state_leg_nominees_state'), ['state'], unique=False)

    if 'statewide_nominees' not in existing:
        op.create_table('statewide_nominees',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('state', sa.String(length=2), nullable=False),
        sa.Column('cycle_year', sa.Integer(), nullable=False),
        sa.Column('office', sa.String(length=32), nullable=False),
        sa.Column('district', sa.String(length=8), nullable=True),
        sa.Column('party', sa.String(length=1), nullable=False),
        sa.Column('display_name', sa.String(length=200), nullable=False),
        sa.Column('source_name', sa.String(length=200), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('state', 'cycle_year', 'office', 'district', 'party', 'display_name', name='uq_statewide_nominee_seat_party_name')
        )
        with op.batch_alter_table('statewide_nominees', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_statewide_nominees_cycle_year'), ['cycle_year'], unique=False)
            batch_op.create_index(batch_op.f('ix_statewide_nominees_state'), ['state'], unique=False)

    if 'stock_trades_pipeline_runs' not in existing:
        op.create_table('stock_trades_pipeline_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('house_trades_ingested', sa.Integer(), nullable=False),
        sa.Column('senate_trades_ingested', sa.Integer(), nullable=False),
        sa.Column('president_trades_ingested', sa.Integer(), nullable=False),
        sa.Column('elapsed_seconds', sa.Float(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('progress_detail', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'supplementary_pipeline_runs' not in existing:
        op.create_table('supplementary_pipeline_runs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('current_phase', sa.String(), nullable=True),
        sa.Column('explore_docs_ingested', sa.Integer(), nullable=False),
        sa.Column('justices_scored', sa.Integer(), nullable=False),
        sa.Column('justices_skipped', sa.Boolean(), nullable=False),
        sa.Column('committee_leadership_refreshed', sa.Boolean(), nullable=False),
        sa.Column('committee_leadership_skipped', sa.Boolean(), nullable=False),
        sa.Column('district_pvi_refreshed', sa.Boolean(), nullable=False),
        sa.Column('district_pvi_skipped', sa.Boolean(), nullable=False),
        sa.Column('presidents_updated', sa.Integer(), nullable=False),
        sa.Column('elapsed_seconds', sa.Float(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('progress_detail', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'timeline_entries' not in existing:
        op.create_table('timeline_entries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date', sa.String(length=10), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('policy_areas', sa.Text(), nullable=False),
        sa.Column('source_url', sa.String(length=1000), nullable=True),
        sa.Column('source_name', sa.String(length=200), nullable=True),
        sa.Column('monitor_slug', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_timeline_entries_date'), ['date'], unique=True)

    if 'week_summaries' not in existing:
        op.create_table('week_summaries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('week_num', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.String(length=10), nullable=False),
        sa.Column('end_date', sa.String(length=10), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('top_policy_areas', sa.Text(), nullable=False),
        sa.Column('entry_count', sa.Integer(), nullable=False),
        sa.Column('generated_at', sa.DateTime(), nullable=False),
        sa.Column('bsky_posted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('week_summaries', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_week_summaries_year'), ['year'], unique=False)

    if 'year_summaries' not in existing:
        op.create_table('year_summaries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('top_policy_areas', sa.Text(), nullable=False),
        sa.Column('entry_count', sa.Integer(), nullable=False),
        sa.Column('generated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('year_summaries', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_year_summaries_year'), ['year'], unique=True)

    if 'campaign_promises' not in existing:
        op.create_table('campaign_promises',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('senator_id', sa.String(), nullable=False),
        sa.Column('promise_text', sa.Text(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('alignment', sa.String(), nullable=False),
        sa.Column('related_votes', sa.Text(), nullable=False),
        sa.Column('related_bills', sa.Text(), nullable=False),
        sa.Column('analysis', sa.Text(), nullable=False),
        sa.Column('party_alignment', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['senator_id'], ['senators.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('campaign_promises', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_campaign_promises_senator_id'), ['senator_id'], unique=False)

    if 'candidates' not in existing:
        op.create_table('candidates',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('race_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('party', sa.String(), nullable=False),
        sa.Column('incumbent_challenge', sa.String(length=1), nullable=True),
        sa.Column('has_raised_funds', sa.Boolean(), nullable=False),
        sa.Column('candidate_status', sa.String(length=1), nullable=True),
        sa.Column('confirmed_general', sa.Boolean(), nullable=False),
        sa.Column('on_primary_ballot', sa.Boolean(), nullable=False),
        sa.Column('last_coverage_search', sa.DateTime(), nullable=True),
        sa.Column('contributions', sa.Float(), nullable=True),
        sa.Column('disbursements', sa.Float(), nullable=True),
        sa.Column('cash_on_hand', sa.Float(), nullable=True),
        sa.Column('individual_itemized_contributions', sa.Float(), nullable=True),
        sa.Column('last_financials_sync', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('candidates', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_candidates_race_id'), ['race_id'], unique=False)

    if 'donors' not in existing:
        op.create_table('donors',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('senator_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('total', sa.Float(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('pac_sponsor', sa.String(), nullable=True),
        sa.Column('pac_industry', sa.String(), nullable=True),
        sa.Column('pac_analysis', sa.Text(), nullable=True),
        sa.Column('committee_type', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['senator_id'], ['senators.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('donors', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_donors_senator_id'), ['senator_id'], unique=False)

    if 'industry_donations' not in existing:
        op.create_table('industry_donations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('senator_id', sa.String(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('total', sa.Float(), nullable=False),
        sa.Column('percentage', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['senator_id'], ['senators.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('industry_donations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_industry_donations_senator_id'), ['senator_id'], unique=False)

    if 'justice_votes' not in existing:
        op.create_table('justice_votes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('justice_id', sa.String(), nullable=False),
        sa.Column('case_id', sa.String(), nullable=False),
        sa.Column('case_name', sa.String(), nullable=False),
        sa.Column('case_term', sa.String(), nullable=False),
        sa.Column('decided_date', sa.String(), nullable=True),
        sa.Column('vote', sa.String(), nullable=False),
        sa.Column('opinion_type', sa.String(), nullable=False),
        sa.Column('is_unanimous', sa.Boolean(), nullable=False),
        sa.Column('is_close', sa.Boolean(), nullable=False),
        sa.Column('majority_votes', sa.Integer(), nullable=False),
        sa.Column('minority_votes', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['justice_id'], ['justices.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('justice_id', 'case_id', name='uq_justice_vote_justice_case')
        )
        with op.batch_alter_table('justice_votes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_justice_votes_justice_id'), ['justice_id'], unique=False)

    if 'key_votes' not in existing:
        op.create_table('key_votes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('senator_id', sa.String(), nullable=False),
        sa.Column('bill_name', sa.String(), nullable=False),
        sa.Column('bill_id', sa.String(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('vote', sa.String(), nullable=False),
        sa.Column('policy_area', sa.String(), nullable=False),
        sa.Column('policy_areas', sa.Text(), nullable=False),
        sa.Column('party_alignment_weight', sa.Float(), nullable=False),
        sa.Column('stance', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('party_leaning', sa.String(), nullable=True),
        sa.Column('voted_with_party', sa.Boolean(), nullable=True),
        sa.Column('vote_category', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['senator_id'], ['senators.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('key_votes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_key_votes_senator_id'), ['senator_id'], unique=False)

    if 'lobbying_matches' not in existing:
        op.create_table('lobbying_matches',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('senator_id', sa.String(), nullable=False),
        sa.Column('lobbyist_org', sa.String(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('lobbying_spend', sa.Float(), nullable=False),
        sa.Column('donation_to_senator', sa.Float(), nullable=False),
        sa.Column('bills_influenced', sa.Text(), nullable=False),
        sa.Column('senator_vote_aligned', sa.Boolean(), nullable=True),
        sa.Column('is_consensus_vote', sa.Boolean(), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['senator_id'], ['senators.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('lobbying_matches', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_lobbying_matches_senator_id'), ['senator_id'], unique=False)

    if 'monitor_updates' not in existing:
        op.create_table('monitor_updates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('monitor_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.String(length=10), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('source_url', sa.String(length=1000), nullable=False),
        sa.Column('source_name', sa.String(length=200), nullable=False),
        sa.Column('article_title', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['monitor_id'], ['national_monitors.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('monitor_updates', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_monitor_updates_date'), ['date'], unique=False)
            batch_op.create_index(batch_op.f('ix_monitor_updates_monitor_id'), ['monitor_id'], unique=False)

    if 'president_trades' not in existing:
        op.create_table('president_trades',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('president_id', sa.String(), nullable=False),
        sa.Column('ticker', sa.String(), nullable=True),
        sa.Column('asset_name', sa.String(), nullable=False),
        sa.Column('owner', sa.String(), nullable=False),
        sa.Column('transaction_type', sa.String(), nullable=False),
        sa.Column('transaction_date', sa.String(), nullable=False),
        sa.Column('disclosure_date', sa.String(), nullable=False),
        sa.Column('days_to_disclose', sa.Integer(), nullable=False),
        sa.Column('amount_low', sa.Float(), nullable=False),
        sa.Column('amount_high', sa.Float(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('source_url', sa.String(), nullable=False),
        sa.Column('filing_id', sa.String(), nullable=False),
        sa.Column('parse_confidence', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['president_id'], ['presidents.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('president_trades', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_president_trades_filing_id'), ['filing_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_president_trades_president_id'), ['president_id'], unique=False)

    if 'race_coverage_items' not in existing:
        op.create_table('race_coverage_items',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('race_id', sa.String(), nullable=False),
        sa.Column('source_type', sa.String(length=10), nullable=False),
        sa.Column('source_name', sa.String(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('author', sa.String(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('fetched_at', sa.DateTime(), nullable=False),
        sa.Column('matched_candidate_id', sa.String(), nullable=True),
        sa.Column('match_basis', sa.String(length=20), nullable=True),
        sa.Column('bsky_posted_at', sa.DateTime(), nullable=True),
        sa.Column('bsky_posted', sa.Boolean(), nullable=False),
        sa.Column('relevance', sa.Float(), nullable=True),
        sa.Column('has_advocacy', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['race_id'], ['races.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('race_id', 'url', name='uq_race_coverage_race_url')
        )
        with op.batch_alter_table('race_coverage_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_race_coverage_items_race_id'), ['race_id'], unique=False)

    if 'rep_campaign_promises' not in existing:
        op.create_table('rep_campaign_promises',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('representative_id', sa.String(), nullable=False),
        sa.Column('promise_text', sa.Text(), nullable=False),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('alignment', sa.String(), nullable=False),
        sa.Column('related_votes', sa.Text(), nullable=False),
        sa.Column('related_bills', sa.Text(), nullable=False),
        sa.Column('analysis', sa.Text(), nullable=False),
        sa.Column('party_alignment', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rep_campaign_promises', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rep_campaign_promises_representative_id'), ['representative_id'], unique=False)

    if 'rep_donors' not in existing:
        op.create_table('rep_donors',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('representative_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('total', sa.Float(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('pac_sponsor', sa.String(), nullable=True),
        sa.Column('pac_industry', sa.String(), nullable=True),
        sa.Column('pac_analysis', sa.Text(), nullable=True),
        sa.Column('committee_type', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rep_donors', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rep_donors_representative_id'), ['representative_id'], unique=False)

    if 'rep_industry_donations' not in existing:
        op.create_table('rep_industry_donations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('representative_id', sa.String(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('total', sa.Float(), nullable=False),
        sa.Column('percentage', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rep_industry_donations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rep_industry_donations_representative_id'), ['representative_id'], unique=False)

    if 'rep_key_votes' not in existing:
        op.create_table('rep_key_votes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('representative_id', sa.String(), nullable=False),
        sa.Column('bill_name', sa.String(), nullable=False),
        sa.Column('bill_id', sa.String(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('vote', sa.String(), nullable=False),
        sa.Column('policy_area', sa.String(), nullable=False),
        sa.Column('policy_areas', sa.Text(), nullable=False),
        sa.Column('party_alignment_weight', sa.Float(), nullable=False),
        sa.Column('stance', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('party_leaning', sa.String(), nullable=True),
        sa.Column('voted_with_party', sa.Boolean(), nullable=True),
        sa.Column('vote_category', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rep_key_votes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rep_key_votes_representative_id'), ['representative_id'], unique=False)

    if 'rep_lobbying_matches' not in existing:
        op.create_table('rep_lobbying_matches',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('representative_id', sa.String(), nullable=False),
        sa.Column('lobbyist_org', sa.String(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('lobbying_spend', sa.Float(), nullable=False),
        sa.Column('donation_to_representative', sa.Float(), nullable=False),
        sa.Column('bills_influenced', sa.Text(), nullable=False),
        sa.Column('representative_vote_aligned', sa.Boolean(), nullable=True),
        sa.Column('is_consensus_vote', sa.Boolean(), nullable=True),
        sa.Column('description', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rep_lobbying_matches', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rep_lobbying_matches_representative_id'), ['representative_id'], unique=False)

    if 'rep_sponsored_bills' not in existing:
        op.create_table('rep_sponsored_bills',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('representative_id', sa.String(), nullable=False),
        sa.Column('bill_id', sa.String(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('introduced_date', sa.String(), nullable=False),
        sa.Column('latest_action', sa.Text(), nullable=False),
        sa.Column('latest_action_date', sa.String(), nullable=False),
        sa.Column('policy_area', sa.String(), nullable=False),
        sa.Column('policy_areas', sa.Text(), nullable=False),
        sa.Column('party_leaning', sa.String(), nullable=True),
        sa.Column('congress', sa.Integer(), nullable=False),
        sa.Column('bill_type', sa.String(), nullable=False),
        sa.Column('is_law', sa.Boolean(), nullable=False),
        sa.Column('stage', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rep_sponsored_bills', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rep_sponsored_bills_bill_id'), ['bill_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_rep_sponsored_bills_representative_id'), ['representative_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_rep_sponsored_bills_stage'), ['stage'], unique=False)

    if 'rep_stock_trades' not in existing:
        op.create_table('rep_stock_trades',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('representative_id', sa.String(), nullable=False),
        sa.Column('ticker', sa.String(), nullable=True),
        sa.Column('asset_name', sa.String(), nullable=False),
        sa.Column('owner', sa.String(), nullable=False),
        sa.Column('transaction_type', sa.String(), nullable=False),
        sa.Column('transaction_date', sa.String(), nullable=False),
        sa.Column('disclosure_date', sa.String(), nullable=False),
        sa.Column('days_to_disclose', sa.Integer(), nullable=False),
        sa.Column('amount_low', sa.Float(), nullable=False),
        sa.Column('amount_high', sa.Float(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('source_url', sa.String(), nullable=False),
        sa.Column('filing_id', sa.String(), nullable=False),
        sa.Column('parse_confidence', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('rep_stock_trades', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_rep_stock_trades_filing_id'), ['filing_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_rep_stock_trades_representative_id'), ['representative_id'], unique=False)

    if 'sponsored_bills' not in existing:
        op.create_table('sponsored_bills',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('senator_id', sa.String(), nullable=False),
        sa.Column('bill_id', sa.String(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('introduced_date', sa.String(), nullable=False),
        sa.Column('latest_action', sa.Text(), nullable=False),
        sa.Column('latest_action_date', sa.String(), nullable=False),
        sa.Column('policy_area', sa.String(), nullable=False),
        sa.Column('policy_areas', sa.Text(), nullable=False),
        sa.Column('party_leaning', sa.String(), nullable=True),
        sa.Column('congress', sa.Integer(), nullable=False),
        sa.Column('bill_type', sa.String(), nullable=False),
        sa.Column('is_law', sa.Boolean(), nullable=False),
        sa.Column('stage', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['senator_id'], ['senators.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('sponsored_bills', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_sponsored_bills_bill_id'), ['bill_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_sponsored_bills_senator_id'), ['senator_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_sponsored_bills_stage'), ['stage'], unique=False)

    if 'stock_trades' not in existing:
        op.create_table('stock_trades',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('senator_id', sa.String(), nullable=False),
        sa.Column('ticker', sa.String(), nullable=True),
        sa.Column('asset_name', sa.String(), nullable=False),
        sa.Column('owner', sa.String(), nullable=False),
        sa.Column('transaction_type', sa.String(), nullable=False),
        sa.Column('transaction_date', sa.String(), nullable=False),
        sa.Column('disclosure_date', sa.String(), nullable=False),
        sa.Column('days_to_disclose', sa.Integer(), nullable=False),
        sa.Column('amount_low', sa.Float(), nullable=False),
        sa.Column('amount_high', sa.Float(), nullable=False),
        sa.Column('industry', sa.String(), nullable=False),
        sa.Column('source_url', sa.String(), nullable=False),
        sa.Column('filing_id', sa.String(), nullable=False),
        sa.Column('parse_confidence', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['senator_id'], ['senators.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('stock_trades', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_stock_trades_filing_id'), ['filing_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_stock_trades_senator_id'), ['senator_id'], unique=False)


def downgrade() -> None:
    raise NotImplementedError("the baseline is not reversible: downgrading it would drop every table")
