/**
 * Reading the public API's OpenAPI spec (GET /api/public/v1/openapi.json,
 * generated by FastAPI from the routes) for the /developers page. Only the
 * subset FastAPI emits for those routes is modelled.
 */

export interface Schema {
  type?: string;
  $ref?: string;
  items?: Schema;
  anyOf?: Schema[];
  enum?: (string | number)[];
  const?: string | number;
  properties?: Record<string, Schema>;
  required?: string[];
  additionalProperties?: boolean | Schema;
  description?: string;
  default?: unknown;
  minimum?: number;
  maximum?: number;
}

export interface Parameter {
  name: string;
  in: "path" | "query";
  required?: boolean;
  description?: string;
  schema: Schema;
}

export interface Operation {
  operationId: string;
  summary?: string;
  description?: string;
  tags?: string[];
  parameters?: Parameter[];
  responses: Record<string, { description?: string; content?: Record<string, { schema: Schema }> }>;
}

export interface Spec {
  info: {
    title: string;
    version: string;
    summary?: string;
    description?: string;
    /** Requests per minute per address (api/public.py adds it; rate_limit.PUBLIC_READ_LIMIT). */
    "x-rate-limit-per-minute"?: number;
  };
  paths: Record<string, Record<string, Operation>>;
  components?: { schemas?: Record<string, Schema> };
  /** Group order and introductions (FastAPI's openapi_tags). */
  tags?: { name: string; description?: string }[];
}

export interface Endpoint {
  method: string;
  path: string;
  op: Operation;
}

export interface EndpointGroup {
  tag: string;
  description?: string;
  endpoints: Endpoint[];
}

/** Endpoints grouped by their first tag: declared tags in their declared
 *  order, then any others in order of appearance. */
export function endpointsByTag(spec: Spec): EndpointGroup[] {
  const groups = new Map<string, EndpointGroup>(
    (spec.tags ?? []).map((t) => [
      t.name,
      { tag: t.name, description: t.description, endpoints: [] },
    ])
  );
  for (const [path, ops] of Object.entries(spec.paths)) {
    for (const [method, op] of Object.entries(ops)) {
      const tag = op.tags?.[0] ?? "Other";
      if (!groups.has(tag)) groups.set(tag, { tag, endpoints: [] });
      groups.get(tag)!.endpoints.push({ method: method.toUpperCase(), path, op });
    }
  }
  return [...groups.values()].filter((g) => g.endpoints.length > 0);
}

/** Follows a $ref into components; anything else is returned as is. */
export function resolve(schema: Schema, spec: Spec): Schema {
  if (!schema.$ref) return schema;
  const name = schema.$ref.split("/").pop() ?? "";
  return spec.components?.schemas?.[name] ?? {};
}

/** "FundingSchema" -> "Funding", "PublicSenatorRowSchema" -> "Senator row". */
export function schemaName(ref: string): string {
  const bare = (ref.split("/").pop() ?? ref).replace(/^Public/, "").replace(/Schema$/, "");
  const words = bare.replace(/([a-z])([A-Z])/g, "$1 $2").toLowerCase();
  return words.charAt(0).toUpperCase() + words.slice(1);
}

/** A plain-words type: "string", "list of Senator row", "D, R or I", "number or null". */
export function typeLabel(schema: Schema): string {
  if (schema.$ref) return schemaName(schema.$ref);
  if (schema.enum) return joinOr(schema.enum.map(String));
  if (schema.const !== undefined) return String(schema.const);
  if (schema.anyOf) {
    const kinds = schema.anyOf.filter((s) => s.type !== "null").map(typeLabel);
    const nullable = schema.anyOf.some((s) => s.type === "null");
    return nullable ? `${joinOr(kinds)}, or null` : joinOr(kinds);
  }
  if (schema.type === "array")
    return `list of ${schema.items ? typeLabel(schema.items) : "values"}`;
  if (
    schema.type === "object" &&
    schema.additionalProperties &&
    typeof schema.additionalProperties === "object"
  ) {
    return `map of ${typeLabel(schema.additionalProperties)}`;
  }
  return schema.type ?? "any";
}

/** A query parameter's type: optional ones are simply left out, so no
 *  "or null"; a numeric range is stated. */
export function paramTypeLabel(schema: Schema): string {
  const value = schema.anyOf?.filter((s) => s.type !== "null") ?? [schema];
  const label = value.length === 1 ? typeLabel(value[0]) : typeLabel({ anyOf: value });
  const { minimum: lo, maximum: hi } = value.length === 1 ? value[0] : schema;
  if (lo !== undefined && hi !== undefined) return `${label}, ${lo} to ${hi}`;
  if (lo !== undefined) return `${label}, at least ${lo}`;
  return label;
}

/** Splits `code` spans out of prose, as the routes' docstrings write them. */
export function codeSpans(text: string): { code: boolean; text: string }[] {
  return text
    .split(/`([^`]+)`/)
    .map((part, i) => ({ code: i % 2 === 1, text: part }))
    .filter((part) => part.text);
}

function joinOr(items: string[]): string {
  return items.length < 2
    ? (items[0] ?? "")
    : `${items.slice(0, -1).join(", ")} or ${items.at(-1)}`;
}

/** The object schema a field holds, if any (through a list, a $ref or a nullable). */
export function nestedObject(schema: Schema, spec: Spec): Schema | null {
  const inner = schema.type === "array" && schema.items ? schema.items : schema;
  const candidate = inner.anyOf?.find((s) => s.type !== "null") ?? inner;
  const target = resolve(candidate, spec);
  return target.properties ? target : null;
}

/** The 200 response's body schema, resolved. */
export function responseSchema(op: Operation, spec: Spec): Schema | null {
  const body = op.responses["200"]?.content?.["application/json"]?.schema;
  return body ? resolve(body, spec) : null;
}
